// Bopca Community Center fan skills
export const bopcaSkills: { name: string; description: string }[] = [
  { name: `Animal Mimicry`, description: `You can convincingly imitate animal sounds and mannerisms (but not appearance...that's a different skill). Higher skill levels may allow you to both understand and communicate simple messages with animals.` },
  { name: `B-Movie Brain Rot`, description: `Congratulations. You’ve spent so much time rotting your subconscious with low-budget cinematic trash that the System has decided to reward your lack of a social life. 
Skill Level: 1 (Initiate) Passive Effect: You can instantly categorize any shambling, necrotic monstrosity by its cinematic archetype. 
Active Effect: Once per floor, you can scream "That’s a Romero Shambler!" to gain a +5% Movement Speed buff, because you know exactly how slow those bastards are. 
The Lore (Or Lack Thereof) Now, look. Do "zombies" exist? Well, let’s be honest: the Universe is a big, weird, incredibly violent place. Usually, when something starts eating your neighbors, it’s not because of a "solanum virus" or a "secret government chemical." It’s usually because some Bored Celestial decided to reanimate a pile of organic waste to see if it could win a cage match against a bipedal goat. In the Dungeon, we don’t call them "zombies." That’s trademark infringement, and the Borant Corporation is very litigious. 
Here, we have: 
Exhumed Debtors: They’re slow, they smell like damp cardboard, and they’re technically still under contract. 
Necrotic Bio-Drones: These are the ones that run. They don't want your brains; they want your carbon. 
The Bloated Producers:If it’s fat, glowing green, and looks like it’s about to pop? Don’t stand downwind. 

Current Status Since the AI running this crawl is currently obsessed with "Classic Earth Horror Tropes," your skill is actually functional. However, if we hit a floor themed after 18th-century French ballrooms, your knowledge of Zombieland’s "Double Tap" rule is going to be about as useful as a chocolate teapot.

 NEW ACHIEVEMENT: The Couch Potato’s Revenge Reward: You’ve received a Bronze Enthusiast Box Description:You’ve watched so many movies you actually think you’re prepared for an apocalypse. You aren’t. But hey, at least you’ll die knowing the difference between a "Runner" and a "Stalker."` },
  { name: `Bartender`, description: `Knows how to mix a good coctail. 10% Bonus to potion / poison making.` },
  { name: `Boasting`, description: `Your ability to boast is impressive(ly annoying)! You never pass up a chance to brag about your exploits, and specifically annoy those around you with them. Make an opposed skill check with CHA+Skill_Rank against a target creature. On a success they become annoyed with you and are much more likely to attack you. 
Rank 5: You can target any number of creatures in sight. Roll your check once and compare against each of their values. 
Rank 10: Your bragging is beginning to become truly frustrating. Now, if a creature taunted by this ability fails to harm you on their turn for whatever reason, they have a chance to damage themself. If their attack roll would hit themself, they take damage from their own hit. 
Rank 15: Your legendary boasting manifests shifts in reality - on a successful check with this skill the Dungeon conforms to your boast. For example you might brag about being the "Best in Dungeon" and suddenly find yourself tagged with a purple ribbon labeled "Best In Dungeon".` },
  { name: `Botanist`, description: `40% Bonus to plant ID and use. Gets easily distracted by plants.` },
  { name: `Calligraphy`, description: `The art of penmanship and detailed writing. Crawler gains the ability to transcribe spell scrolls with greater chance of success.` },
  { name: `Closet Full of Lies`, description: `(Passive / Active Hybrid) Well, well, well… looks like before you were thrown into a meat grinder for the entertainment of sociopathic galaxy-spanning voyeurs, you spent your time playing dress-up on a backwater planet called Earth. Adorable. Truly. Nothing says “I’m prepared for interdimensional survival” like hot glue burns and a suspicious number of wigs. Good news, crawler—turns out pretending to be someone else is actually useful down here. Effect: Your experience with cosplay doesn’t just make you look the part—it helps you be the part. Base Bonus (Always Active): All disguises gain enhanced visual accuracy and cohesion, while subtle behavioral mimicry—posture, idle movements, and confidence—naturally improves overall believability. Disguise Self Synergy: Illusion-based disguises become more realistic and stable, require less mana to maintain, and automatically smooth out minor visual inconsistencies in real time. Social Deception Boost: You are more convincing while disguised, making others less likely to question you during normal interactions and more resistant to casual scrutiny. Active Ability – “Convention Mode” Once per day, you can lock in and perfectly mirror a target you can see, gaining a sharp edge in deception while briefly making others second-guess what they’re seeing. Passive Flavor Bonus: You move comfortably in ridiculous outfits, patch gear with whatever’s on hand, and commit to the bit harder than is ever reasonable. Drawback: You may feel compelled to explain your “build” to people who absolutely do not care. Dungeon Tip: If you’re going to fake it, make sure you can survive being found out.` },
  { name: `Cosplay / Reeactor`, description: `Cosplay/Reenactor: Congratulations! You are a mega nerd! Normies don't care about that awesome set of blackened riveted chainmail you bought from Amazon but you do and you will argue with anyone that it isn't actually called chainmail! You get bonuses to using any weapon, armor or items in the dungeon that you had used during your time LARPing with your fellow neeerrrrds! Bonuses depend on your knowledge and familiarity with your area of nerdity. You nerd!` },
  { name: `Doom Scrolling`, description: `Spent more than an hour a day in the week leading up to the collapse watching pointless videos on social media. Crawler gains the ability to see how many viewers a crawler currently has when meeting them and is able to watch a quick 20 second short highlighting the crawlers last 24 hours.` },
  { name: `Dowsing`, description: `You are able to use a forked stick or other implements to find underground water, minerals, or other hidden substances. Supposedly. It's probably a hoax...or is it?` },
  { name: `EMT`, description: `Bonus to first aid and non-magical healing.  Calm under pressure.` },
  { name: `Engineer`, description: `Provides Bonus 30% to design and build skills. Designs and builds duration takes longer because if obsessive attention to detail.` },
  { name: `Geocaching`, description: `You have a keen eye, granting you a bonus on checks to find clues, especially those related to buried treasure.` },
  { name: `Gongoozling`, description: `You have an affinity for narrow waterways, especially canals. Not sure how many canals you'll see down here in the World Dungeon, but if you do, boy I tell you, you will find it VERY interesting. Gongoozling is the leisurely British pastime of watching activity on canals, such as passing narrowboats, locks opening, and wildlife. Derived from 19th-century Lincolnshire dialect meaning to stare, a "gongoozler" observes without participating. It is a relaxing, often meditative hobby popular along UK waterways, sometimes jokingly compared to trainspotting.` },
  { name: `Hacking`, description: `hacking (int) opposed by any robot/automaton you interact with that is not allied with you.  as you get good enough (15+) you start getting better base like ai favor cause you are able to start messing with the AI itself.` },
  { name: `Hide and Seek`, description: `An Earth based skill that everyone on earth starts with a basic proficiency in due to its inclusion in childhood games across most continents` },
  { name: `Hypocrisy Tourist`, description: `Ability to belittle others for doing the exact thing they proceed to do but worse. Crawler gains the inability to see their own actions for what they are and continues to live the rest of their days in an ignorant bliss, but probably with less friends.` },
  { name: `Intimidating Prowess`, description: `(Passive/Opposed) This skill represents just how intimidating you look doing anything. Whenever you critically succeed on a check (natural 20) you can choose to intimidate another creature who witnessed your power. Roll an Opposed Skill Check (Charisma+Skill Rank) against that creature's Charisma. On a success, their next check/attack has a -1d6. 
Level 5. This now triggers whenever you roll a Spectacular Success as well. (10+ above the Difficulty) 
Level 10. Now targets any number of creatures who witnessed your power. (Roll one check, compare against each opposed creatures' stat) 
Level 15. Instead of a -1d6 to their next check you can instead choose to paralyze the target with fear. They are incapable of doing anything but run away from you on their next turn.` },
  { name: `Irish Heritage`, description: `Being Irish: Gain a 15% Resistance to any poisonous liquids ingested` },
  { name: `Knitting`, description: `Knitting Every time you knit, there's a 10% chance of dropping a stitch, and a 5% chance of fucking up the project royally. Level 1: You know how to Knit and Purl, and can knit a simple scarf. Level 5: You now know how kfb, k2tog, Tink Back, and k1tbl, k2togtbl, and so many more! You can now make shawls that could look like they were made by a little old grandma! Go you! Level 10: You now have the skills to make socks and sweaters. The real question: do you dare risk the dreaded Curse of the Boyfriend Sweater? (There is a 15% chance of invoking the Curse of the Boyfriend Sweater.) 
SPELL: Curse of the Boyfriend Sweater It's okay, I know breakups are hard. It just wasn't meant to be. Upon completion of the sweater, everyone in your party is immediately teleported to a different location within the local city. Good luck with trying to get back together!  

LOL! Long-time knitter here, and I thought this would be hilarious! To explain:
K: Knit stitch - Knitting every row creates a bumpy texture.
P: Purl stich (basically the knit stich, but backwards). Alternating rows of Knits and Purls creates a fabric that's bumpy on one side and flat/smooth on the other.
kfb: Knit Front and Back (creates 2 stitches out of 1).
k2tog: Knit 2 Together (reduces 2 stitches into 1)
Tink Back: to undo your work or work backwards (Tink is Knit spelled backwards)
k1tbl: Knit 1 through Back Loop (the Knit stitch, but you go through the back of the loop, which twists the stich, and can create an interesting texture).
k2togtbl: Knit 2 through the Back Loop (reduce by 1 stitch, through the back loop - twists the stitch).

But, honestly, I think it's funnier if you're not a knitter and DON'T explain the different terms hahahahha` },
  { name: `Mountaineering`, description: `A passing familarity with the gear and theory of climbing: Level 1: You took a few Rock climbing classes as a tween, and now you have a solid understanding of how to ascend a 15' wall with irregular handhold, while the nearest "adult" looks on holding your belaying rope. +1 to climbing checks. This scales with additional level gains.` },
  { name: `Noodling`, description: `You can go fishing...with nothing but your bare hands! Good luck with the fish down here... Higher levels grant increased damage resistance to your arms below the elbow up to 100%. Let's hope you don't lose too many fingers along the way!` },
  { name: `Rules Memory`, description: `The ability to be able to perfectly remember a thousand different set of rules for various games despite the inability to remember the person’s name from the office who has sat across from you every day for the last year.
Crawler gains the ability to remember any set of instructions or rules regarding to the floor of the dungeon they are currently inhabiting and the ability to perfectly relay these to others crawlers (it does not force them to listen though or ask stupid questions or say ‘let’s just learn as we go’)` },
  { name: `Taxidermy`, description: `Now you have a use for all of those dead mobs you keep stuffing into your inventory. Combine with necromancy spells to create your own horrifying monstrosities!` },
]