import { db } from './client.js'
import { mobTemplates } from './schema.js'

const bopcaMobs = [
  {
    name: `Boom Boxers`,
    description: `These individuals may be square and may look like a speaker tower, but they can punch hard, how hard, well they have mama said knock you out by LL cool J stuck in there head, and they always listen to their mama.`,
    hpMin: 4,
    hpMax: 8,
    effortType: 'basic',
    floor: 1,
    isElite: false,
    isBoss: false,
    abilities: `1d6`,
    notes: ``,
    tags: `humanoid,medium`,
  },
  {
    name: `Centaminotaurtaur`,
    description: `50% Centaur, 50% Minotaur, 100% problematic for your party. This Behemoth is pissed at the world and anything that moves. With the Head/Torso of a Bull and the legs/body of a horse, you don't want to be in his way. No one is quite sure why it happened, maybe because 2 creatures decided to defy all odds when it comes to love, maybe because the Dungeon AI got bored, but one thing is for certain, if you see this monstrosity, it's a bad day for you.`,
    hpMin: 16,
    hpMax: 32,
    effortType: 'weapon',
    floor: 1,
    isElite: false,
    isBoss: false,
    abilities: `1d10 punch
3d8 Bull Rush Charge`,
    notes: ``,
    tags: `creature,large`,
  },
  {
    name: `Cheromb`,
    description: `These are mobs you can use as weapons but be wary  these little buggers are like a hot potato and you never know when they will go off. You have to insult the mob before launching it like a grenade and hope that it doesn’t explode in your hands… but if it doesn’t then it will do massive area explosive damage. They also are very depressed and look like sad potatoes.`,
    hpMin: 4,
    hpMax: 8,
    effortType: 'basic',
    floor: 1,
    isElite: false,
    isBoss: false,
    abilities: `3d6 explosive damage`,
    notes: ``,
    tags: `fairy,small`,
  },
  {
    name: `Crabby Pants`,
    description: `These dog sized crabs have hard prickly shells and are notorious for their dubious lifestyle. Careful because their claws can potentially give you crabs! Yes crab giving crabs! An antidote will be required to deal with the issue and if you don't address it, it will cause slow life drain.
Diseased Debuff: suffer 1hp dmg / day of infection.  Requires an antodote potion, or AGGRESSIVE antibiotics to negate.`,
    hpMin: 8,
    hpMax: 16,
    effortType: 'basic',
    floor: 1,
    isElite: false,
    isBoss: false,
    abilities: `d4 + Diseased debuff`,
    notes: ``,
    tags: `animal,small`,
  },
  {
    name: `Decay Moths`,
    description: `Standard moths...Except they'll gradually eat through your armor if not dealt with (which can only be done in safe rooms) so the longer you leave it the lower your stats... And if you think you can just unequip any valuable armour when you see them, think again You've been hit with the Pocket full of Holes debuff, random items in your inventory will fall out of your inventory until you re- equip your armour. That might not sound so bad as you can pick it back up, but not if you're being chased by a mob ORRRRR, you're carrying something that may explode once removed from your inventory.... something wildly powerful and highly volatile 
A certain Dooms Day item`,
    hpMin: 4,
    hpMax: 8,
    effortType: 'basic',
    floor: 1,
    isElite: false,
    isBoss: false,
    abilities: `1 dmg / round to equipment + Pocket Full of Holes Debuff`,
    notes: ``,
    tags: `animal,tiny`,
  },
  {
    name: `Equitaur`,
    description: `This bipedal equine race of carnivorous appear as heavily muscled humanoid creatures with a head closely resembling a horse whose mouth is filled with sharp fangs. Their bodies are covered in a soft coat and mane that can widely vary in coloration. Aggressive, and quick to anger, Equitaur's are often found on the 3rd floor of the World Dungeon, where they populate regions that emulate the American West. Equitars have been known to sport western gear - cowboy hats, boots with spurs, chaps, shirts with dangly fringe, and are fond of carrying 6 shooter revolvers, and single action rifles. On lower floors there are rumours of Equitaur gangs of "Street Toughs" in leather jackets, and spiked mohawks in their manes, but this is unconfirmed. Equitaur's often travel in herds, with both genders being equally vicious.`,
    hpMin: 4,
    hpMax: 8,
    effortType: 'basic',
    floor: 1,
    isElite: false,
    isBoss: false,
    abilities: `d6 melee
d4 bit
d6 kick
or by weapon type`,
    notes: ``,
    tags: `humanoid,medium`,
  },
  {
    name: `Goodbye Kitty`,
    description: `Mob Threat: Deceptive This white bipedal cat mob wears a cute yellow shirt with blue overalls and sports a red bow hanging on one of its ears. Don't let this adorable little mob fool you, through its cute appearance lies a serial murderer. Brandishing a sharp knife (also adorned with a red bow), the Goodbye Kitty mob would no sooner slit your own throat before you can say, "Aww, Hello Kitty!"`,
    hpMin: 4,
    hpMax: 8,
    effortType: 'basic',
    floor: 1,
    isElite: false,
    isBoss: false,
    abilities: `1d4 Claws  / or by weapon type`,
    notes: ``,
    tags: `psychopathicslasher,medium`,
  },
  {
    name: `Gremlock`,
    description: `A small sprite like creature that looks super cute but at night it changes into a gruesome flesh devouring monster the size of a medium dog and hunts as a pack… think gremlins with more teeth`,
    hpMin: 8,
    hpMax: 16,
    effortType: 'basic',
    floor: 1,
    isElite: false,
    isBoss: false,
    abilities: `1d4 bite`,
    notes: ``,
    tags: `fairy,small`,
  },
  {
    name: `Marmic`,
    description: `Marmic: love or hate them, mimic’s are a staple of dungeon life. But watch out for the Marmic, shaped like a literal tub of marmite, they’ll bite your finger right off, best use a knife to be safe but they’re hard to come by down here.`,
    hpMin: 4,
    hpMax: 8,
    effortType: 'basic',
    floor: 1,
    isElite: false,
    isBoss: false,
    abilities: `1d4 dmg bite`,
    notes: ``,
    tags: `mimic,small`,
  },
  {
    name: `Mimic Slime`,
    description: `This sneaky little sucker is often used as a janitor mob on the early levels. Able to blend into their environment with astonishing ease, these unthinking scavengers share the camouflage abilities of earth creatures like the Earth octopus or chameleon. They are drawn by light, heat, and sound on their quest for food. They grow in size with every meal, and upon reaching 3 HD they often split into two separate mobs. If the environment can sustain them, than can reportedly attain vast sizes over time. There attack is acid based, and can eat through standard leather armor. The real danger is stepping directly into the center of a large mimic slime without ever realizing it was there. Barefoot crawlers are their favourite snack in the dungeon. They can also travel on walls and ceilings to drop from above for a unwelcome surprise.`,
    hpMin: 4,
    hpMax: 8,
    effortType: 'basic',
    floor: 1,
    isElite: false,
    isBoss: false,
    abilities: `2d4 Acid / Lvl`,
    notes: ``,
    tags: `ooze,varies\nlevel1small`,
  },
  {
    name: `Mother Smother`,
    description: `Mother Smother manifests as a towering, soft-bodied figure wrapped in layers of pastel fabric, each embroidered with aggressively cheerful patterns. Her arms—oh yes, plural—extend far beyond natural anatomy, telescoping outward with alarming elasticity. Every hand is equipped with mittens. Padded. Gentle-looking. They are not gentle. Her face is permanently fixed in a loving smile stretched just a bit too wide, eyes gleaming with weaponized concern. A diaper bag the size of a coffin hangs at her side, endlessly producing items no one asked for: juice boxes, wet wipes, emotional guilt. Mother Smother does not want to destroy you. She wants to protect you. From everything. Forever. Including yourself.
Mob Threat: Suffocating (literally and emotionally)`,
    hpMin: 4,
    hpMax: 8,
    effortType: 'basic',
    floor: 1,
    isElite: false,
    isBoss: false,
    abilities: ``,
    notes: ``,
    tags: `physchologicalcontrol,large`,
  },
  {
    name: `Negative Nancy`,
    description: `This mob at face value looks like you, maybe even acts like you, but they are sneaky...they come and suck the fun out of you and your efforts resulting in a drain to your health and stamina until you are unable to move forward and die in frustration. Their negative approach to even the most minute of details has the ability to remove all the fun from your endeavors leaving you questioning your life's choices. Be cautious as this is an infectious mob that it only takes one party member to be infected to ruin your day.`,
    hpMin: 4,
    hpMax: 8,
    effortType: 'basic',
    floor: 1,
    isElite: false,
    isBoss: false,
    abilities: `1d4 health drain\n1d4 temporary debuff to Con`,
    notes: ``,
    tags: `humanoid,medium`,
  },
  {
    name: `Nimbus Angel`,
    description: `The Nimbus Angel, or Cloud Angel is a large whale sized mob that disguises itself as a cloud… drops in on unsuspecting crawlers from above and consumes them.   It’s quite a bit larger and is generally found in open landscape with plenty of sky visible…`,
    hpMin: 4,
    hpMax: 8,
    effortType: 'basic',
    floor: 1,
    isElite: false,
    isBoss: false,
    abilities: `1d6 bite\n3d8 consume`,
    notes: ``,
    tags: `monstrosity,huge`,
  },
  {
    name: `Orcestra`,
    description: `Orcestra Description: The Orcestra are heavily armored orc musicians who wage war through weaponized symphonies. Each member carries an instrument modified into a brutal battlefield tool — trombone cannons, bagpipe flamethrowers, violin bows strung with razor wire, and drum kits that create shockwaves powerful enough to crack castle walls. They travel from kingdom to kingdom in a massive black war wagon called The Tour Bus of Doom, demanding tribute before performing their “final concert.” Their attacks grow stronger the longer they stay in rhythm, forcing adventurers to interrupt songs before the Orcestra reaches its devastating finishing move: The Fortissmash. Bards consider them a disgrace to music. Orcs consider them legends. Everyone else just hopes they don’t ask for an encore.`,
    hpMin: 4,
    hpMax: 8,
    effortType: 'basic',
    floor: 1,
    isElite: false,
    isBoss: false,
    abilities: ``,
    notes: ``,
    tags: `orcvariant,medium`,
  },
  {
    name: `Palm Trees`,
    description: `Palm trees: Vegans love them, non vegans should be terrified of them. These are not your Caribbean destination picture perfect shade creating plants. They have a flexible trunk and instead of leafs, there is a giant hand, yes a giant hand and the end. Depending on the age and length of the palm tree, they can either smack you to the ground or grab you and throw you with force to a distant location. Vegans tho, get a pat on the head and perhaps a palm nut that can be consumed for buffs (I'll let the crawlers decide the buffs). These palm trees are not stationary and can migrate by crawling. In this form the are limited to slaps and smacks.`,
    hpMin: 12,
    hpMax: 24,
    effortType: 'weapon',
    floor: 1,
    isElite: false,
    isBoss: false,
    abilities: `1d10 smush damage`,
    notes: ``,
    tags: `sentientvegetation,large`,
  },
  {
    name: `The Granite-Tooth Striped Bastard`,
    description: `(Level 12) ​Don’t let the twitchy nose and the Disney-esque scampering fool you. In the world of the Dungeon, these fuzzy little land-pirates are a literal plague upon anything made of stone, mortar, or hope. While a lone chipmunk is just a snack for a stray cat, a Scurry of them is a demolition crew with high-speed cameras and a bad attitude. ​\n\nThe Stats ​Type: Beast / Siege Specialist ​Threat Level: Low (Individual) / Catastrophic (Swarm) ​\nSpecialty: Structural Sabotage and Inventory Theft \n​Abilities ​Foundation Fracture: These aren't normal teeth. These rodents have been magically enhanced to chew through granite like it’s over-ripened brie. If they find a seam in your fortress wall, they’ll burrow in, expand their pouches with debris, and leave your "unbreakable" tower looking like a game of Jenga played by a drunk giant. ​The "Cheeky" Hoard: Think your healing potions are safe in that chest? Think again. These bastards can unhinge their jaws like a python and stuff an entire mana crystal into their face before you can say "get back here." ​\nHyper-Scamper: Good luck hitting them. They move with a frame-rate-breaking jitter that makes them nearly immune to area-of-effect spells. You’ll waste half your stamina swinging at a patch of dirt while they’re already behind you, mocking your parentage. \n​Tactics: The "Wall-Collapse" Maneuver ​They don't fight you directly—that would be too honest. Instead, the Scurry works in a coordinated rhythm. While the "Distraction Squad" chirps and dances just out of reach, the "Demolition Squad" burrows into the primary load-bearing walls of your base. ​Warning: If you hear a high-pitched chitter-chitter-chip coming from inside your floorboards, it’s already too late. You aren't defending a fortress anymore; you’re standing in a very expensive pile of gravel. ​`,
    hpMin: 4,
    hpMax: 8,
    effortType: 'basic',
    floor: 1,
    isElite: false,
    isBoss: false,
    abilities: ``,
    notes: `New Achievement! ​You’ve been "Nipped!" You just looked at a tiny creature with stripes and thought, "Aww, look at his little cheeks!" Well, those cheeks aren't full of acorns, Carl. They’re full of the structural integrity of your home. You’re about to be homeless, and not the "fun" kind where you get to sleep in a dumpster. ​\n\n"Listen, Carl. I know they're fuzzy. I know they have those cute little stripes. But if you let one of those things get near the safe room, I will personally scratch your eyes out. They aren't 'gathering for winter,' Carl. They’re gathering for the inevitable collapse of your dignity."`,
    tags: `beast,small`,
  },
  {
    name: `The Queue Jumper`,
    description: `Motivation: chaos \nThis insidious and mercurial beastie aims to aggravate and destroy your well rehearsed combat tactics and plans! Not to mention severely mess with your patience! Always found lurking near other mobs, The Queue Jumper will switch places with a randomly rolled member of your party or mob, delighting in the ensuing chaos! This minion of the goddess Eris is susceptible to the 'social outrage' debuff inflicted by any form of aggravated noise or action derived from horror at the thought of jumping a queue! \nMechanics: 75% chance to switch places with the next crawler or creature in combat. d20: On ANY roll of a 1, this creature will actually switch not only places but also equipment and clothes with a party member. On any roll of a 20 the creature will immediately transfer 1d4 previously captured lewt to that crawler. \nReward? If captured (requires creature to be rendered unconscious or immobile on 5% health and then tutted at severely - or similar show of social outrage) the creature is transformed into a wearable button of itself. Button may be thrown down or activated in order to: - Switch places with a target of the user's choice - Bypass the usual looting mechanics to gain treasure ahead of the rightful owner - May be used once to gain entry to The Desperado Club if entry is usually prohibited. Button has 25% chance of disappearing after each use.`,
    hpMin: 4,
    hpMax: 8,
    effortType: 'basic',
    floor: 1,
    isElite: false,
    isBoss: false,
    abilities: `1d4`,
    notes: ``,
    tags: `gremlin,small`,
  },
  {
    name: `Bramley Coppertun`,
    description: `This Dwarven distiller is attempting cross the overcity with a wagon loaded with casks - the last remaining stock of his dwindling ancestral supply of the Clan's whiskey distillery. Pursued by thieves, brigades, and thirsty Crawlers, Branley will offer to hire the Party to escort him on his travels across the floor.`,
    hpMin: 30,
    hpMax: 60,
    effortType: 'weapon',
    floor: 2,
    isElite: true,
    isBoss: false,
    abilities: `Coppertun Run`,
    notes: `Level 50`,
    tags: `elite,dwarf,distiller`,
  },
  {
    name: `Captain Jayne Caboose`,
    description: `This guy is a member of the town guard who kinda looks like Adam Baldwin in what appears to be Leather Plate armor... holds a rifle like weapon that seems to be some kind of compact compound crossbow (might be a reward). He's physically imposing, clearly skilled, but clearly a little dumb and is willing to give up way too much information with light prodding. He's investigating the headless corpse of another guard Lt John Washington. Caboose will show up from time to time and will probably be the final victim they are trying to rescue in the boss fight when the ritual is in danger of completion.`,
    hpMin: 30,
    hpMax: 60,
    effortType: 'weapon',
    floor: 2,
    isElite: true,
    isBoss: false,
    abilities: ``,
    notes: `Level 50`,
    tags: `elite,human,guard`,
  },
  {
    name: `Carolina Reaper`,
    description: `The head of this expedition is a fedora topped lady named Carolina Reaper Lv48 Elite. She's seeking an artifact that's hidden in a temple in ruins that primitives are occupying. She attempts to enlist the crawlers to help her delve deep into their territory to collect the artifact, what she's really looking for a distraction, a suicide mission. Should the crawlers agree, they head out and eventually come to realize they've been sent to the wrong place as a distraction.`,
    hpMin: 30,
    hpMax: 60,
    effortType: 'weapon',
    floor: 2,
    isElite: true,
    isBoss: false,
    abilities: ``,
    notes: `Level 48`,
    tags: `elite`,
  },
  {
    name: `Fetin the Frugal Feline`,
    description: `He is a Tabaxi, on his mother’s side, who runs a local food establishment that serves famous dishes made entirely from local fauna. You meet Fetin bumbling around the local forest looking exhausted. He offers you a free hearty meal and an old recipe book if you can help him collect the ingredients on his list: Gecko Green Beans, Quartz Mushrooms, and Minotoads.`,
    hpMin: 30,
    hpMax: 60,
    effortType: 'weapon',
    floor: 2,
    isElite: true,
    isBoss: false,
    abilities: ``,
    notes: `Level 42`,
    tags: `elite,tabaxi`,
  },
  {
    name: `Forlorna Dune`,
    description: `Betrayed on the night she was to be wed to her true love, Infamous Thomas, Forlorna's jealous bridesmaid pricked ol' Tom with a poisoned rose, immediately turning him to stone. In her rage, Forlorna ripped the bridesmaid to shreds before she could learn the secret to reversing the curse and has been searching for a cure ever since.`,
    hpMin: 30,
    hpMax: 60,
    effortType: 'weapon',
    floor: 2,
    isElite: true,
    isBoss: false,
    abilities: `Not All Who Wander are Lost`,
    notes: `Level 60`,
    tags: `elite`,
  },
  {
    name: `Kellan Ashgrove`,
    description: `A once renown half-elf bard that has fallen out of favour with the elven high court, Kellen has fallen on hard times, relegated to performing in small and medium sized settlements after a mis-step at court. He blames all of his troubles on his current instrument: a badly damaged and un-tuneable lute.`,
    hpMin: 30,
    hpMax: 60,
    effortType: 'weapon',
    floor: 2,
    isElite: true,
    isBoss: false,
    abilities: `The Price of a Song`,
    notes: `Level 50`,
    tags: `elite,halfelf,bard`,
  },
  {
    name: `The Black Knight`,
    description: `Monty Python inspired hedge knight. After 3 days it resurrects on what ever floor the party is on and continues to hunt them unless they carry one of its dismembered appendages in their inventories.`,
    hpMin: 30,
    hpMax: 60,
    effortType: 'weapon',
    floor: 2,
    isElite: true,
    isBoss: false,
    abilities: ``,
    notes: `Level 50`,
    tags: `elite,hedgeknight`,
  },
  {
    name: `V'Kormas Aegisbane`,
    description: `Part 1: He hates mages. And anyone named Andrew. An aged orc barbarian who challenged the God of Magic and was broken. Now he is forced to study magic, but is terrible at it and relies entirely on scrolls. Travels with skeletal mastiff Poe.`,
    hpMin: 30,
    hpMax: 60,
    effortType: 'weapon',
    floor: 2,
    isElite: true,
    isBoss: false,
    abilities: `The Ugly Mirror`,
    notes: `Level 90`,
    tags: `elite,orc,barbarian`,
  },
  // --- ADDED CANONICAL ATLAS MOBS ---
  {
    name: `Hatchling Rust Swarm`,
    description: `A tiny, clicking cloud of metallic beetles that eat through copper wire, discarded metal, and any copper coins in an unstabilized crawler's pockets. The quintessential first tutorial threat.`,
    hpMin: 2,
    hpMax: 4,
    effortType: 'basic',
    floor: 1,
    isElite: false,
    isBoss: false,
    abilities: `1d2 bite`,
    notes: ``,
    tags: `hazard,swarm,tiny`,
  },
  {
    name: `Goblin Scout`,
    description: `Quintessential first floor training fodder. A small green goblin holding a rusty copper knife and sniffing out garbage piles.`,
    hpMin: 4,
    hpMax: 8,
    effortType: 'basic',
    floor: 1,
    isElite: false,
    isBoss: false,
    abilities: `1d4 knife`,
    notes: ``,
    tags: `goblin,small`,
  },
  {
    name: `Goblin Engineer`,
    description: `A goblin wearing cracked leather goggles and carrying a backpack of volatile black powder. Throws clumsy pipe bombs that deal splash fire damage.`,
    hpMin: 6,
    hpMax: 10,
    effortType: 'weapon',
    floor: 1,
    isElite: false,
    isBoss: false,
    abilities: `d6 Pipe Bomb (fire, splash)`,
    notes: ``,
    tags: `goblin,small`,
  },
  {
    name: `Goblin Bomb Bard`,
    description: `A loud, screeching goblin playing a crude lute and singing unhinged heavy metal songs. Buffs other goblins, raising their accuracy and armor class.`,
    hpMin: 8,
    hpMax: 12,
    effortType: 'basic',
    floor: 1,
    isElite: false,
    isBoss: false,
    abilities: `1d4 physical lute smash`,
    notes: `Screeches buffs to nearby goblins.`,
    tags: `goblin,small`,
  },
  {
    name: `Scatterer`,
    description: `A ravenous, Doberman-sized mutant cockroach with thick armor plates and an endless appetite. Swarms in large garbage piles.`,
    hpMin: 8,
    hpMax: 14,
    effortType: 'basic',
    floor: 1,
    isElite: false,
    isBoss: false,
    abilities: `1d6 acid bite`,
    notes: `Bites can infect with sewer disease.`,
    tags: `beast,medium`,
  },
  {
    name: `The Hoarder Boss`,
    description: `A massive, bloated genetic slug-beast made of compacted unwashed laundry, old magazines, and fast-food containers. The first floor Borough Boss.`,
    hpMin: 35,
    hpMax: 60,
    effortType: 'weapon',
    floor: 1,
    isElite: false,
    isBoss: true,
    abilities: `1d10 body slam\n2d6 Trash Avalanche`,
    notes: `Floor 1 Boss`,
    tags: `beast,large,boss`,
  },
  {
    name: `Clurichaun`,
    description: `A small, red-faced leprechaun-like creature wearing overalls and smelling of cheap potato moonshine. Highly deceptive, runs pyramid schemes and trades illegal goods.`,
    hpMin: 12,
    hpMax: 20,
    effortType: 'basic',
    floor: 2,
    isElite: false,
    isBoss: false,
    abilities: `d4 shillelagh\nLiquid Courage (+2 Str, -2 Dex)`,
    notes: ``,
    tags: `humanoid,small`,
  },
  {
    name: `The Krakaren`,
    description: `A massive, screaming, multi-tentacled mutant squid that wears a short, blocky blonde haircut and shrieks demands at crawlers. The Floor 2 Borough Boss.`,
    hpMin: 80,
    hpMax: 120,
    effortType: 'weapon',
    floor: 2,
    isElite: false,
    isBoss: true,
    abilities: `2d6 tentacle whip\nHOA Screech (Silence spellcasters for 1 round)`,
    notes: `Floor 2 Boss`,
    tags: `beast,large,boss`,
  },
]

export async function seedBopcaMobs() {
  console.log('[Seed] Importing Bopca mobs...')
  for (const mob of bopcaMobs) {
    try {
      await db.insert(mobTemplates).values(mob).onConflictDoNothing()
    } catch (e) { /* skip */ }
  }
  console.log('[Seed] mobs imported: ' + bopcaMobs.length)
}
