import { db } from './client.js'
import { items } from './schema.js'

const bopcaItems: any[] = [
  {
    name: `Smokebombs, Firecrackers, Or Flash`,
    description: `smokebombs, firecrackers, or flash powder.`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `junk,bronze`,
  },
  {
    name: `30' Hemp Rope`,
    description: `30' hemp Rope`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `junk,bronze`,
  },
  {
    name: `Small Pack Of Herbs`,
    description: `small pack of herbs of the alchemy`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `junk,bronze`,
  },
  {
    name: `Small Pack Of Scrap`,
    description: `small pack of scrap metal for the crafters`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `junk,bronze`,
  },
  {
    name: `Cans Of Energy Drinks`,
    description: `cans of energy drinks`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `junk,bronze`,
  },
  {
    name: `Coffee And T, Eas`,
    description: `coffee and t, eas`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `junk,bronze`,
  },
  {
    name: `Randoms Bags Of Snack`,
    description: `randoms bags of snack foods (pringles, beef jerky, cheetos, etc...)`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `junk,bronze`,
  },
  {
    name: `Mre Kits`,
    description: `MRE kits`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `junk,bronze`,
  },
  {
    name: `Autographed Collectible Cards`,
    description: `Autographed collectible cards,`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `junk,bronze`,
  },
  {
    name: `200 Loose Keys`,
    description: `200 loose Keys`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `junk,bronze`,
  },
  {
    name: `A "You Can Do`,
    description: `A "You Can Do It" Sign`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `junk,bronze`,
  },
  {
    name: `A 10 Pack Of`,
    description: `A 10 pack of unsharpened #2 HB pencils`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `junk,bronze`,
  },
  {
    name: `A Bag Of Bags`,
    description: `A Bag of Bags`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `junk,bronze`,
  },
  {
    name: `A Blue French Horn`,
    description: `A blue French Horn`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `junk,bronze`,
  },
  {
    name: `A Book Of Dad`,
    description: `A Book of Dad Jokes`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `junk,bronze`,
  },
  {
    name: `A Bookmark`,
    description: `A bookmark`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `junk,bronze`,
  },
  {
    name: `A Box Of 50`,
    description: `A Box of 50 Plastic Sporks`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `junk,bronze`,
  },
  {
    name: `A Box Of Strawberry`,
    description: `A box of strawberry shortcake bandaids,`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `junk,bronze`,
  },
  {
    name: `A Broken Bicycle Chain`,
    description: `A broken bicycle chain`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `junk,bronze`,
  },
  {
    name: `A Button That Causes`,
    description: `A Button that causes the sound of applause to play around you.`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `junk,bronze`,
  },
  {
    name: `A Coupon To (Insert`,
    description: `A coupon to (insert random real world store here) for a new bike. It expired 3 months before the crawl started.`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `junk,bronze`,
  },
  {
    name: `A Doll'S Backpack`,
    description: `A Doll's Backpack`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `junk,bronze`,
  },
  {
    name: `A Figurine Of A`,
    description: `A figurine of a Centaminotaurtaur. It does nothing but portrays the image of a threat to come.`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `junk,bronze`,
  },
  {
    name: `A Fish In A`,
    description: `A fish in a bag`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `junk,bronze`,
  },
  {
    name: `A Map The Size`,
    description: `A Map the size of a gum wrapper`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `junk,bronze`,
  },
  {
    name: `A New Pack Of`,
    description: `A new pack of cigarettes and a lighter. Once opened it's apparent they been half smoked. Some have lipstick stains on the butt.`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `junk,bronze`,
  },
  {
    name: `A Pair Of Socks`,
    description: `A pair of socks with "grandma loves you" stitched into them.`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `junk,bronze`,
  },
  {
    name: `A Potion Of Breath`,
    description: `A potion of Breath Air`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `junk,bronze`,
  },
  {
    name: `A Rubber Duck`,
    description: `A Rubber Duck`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `junk,bronze`,
  },
  {
    name: `A Salmon Thrown At`,
    description: `A salmon thrown at you out of the box.`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `junk,bronze`,
  },
  {
    name: `A Sentient Toaster`,
    description: `A sentient toaster`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `junk,bronze`,
  },
  {
    name: `A Shiny Canadian Quarter`,
    description: `A shiny Canadian Quarter`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `junk,bronze`,
  },
  {
    name: `A Shiny First Edition`,
    description: `A Shiny First Edition Charizard Card`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `junk,bronze`,
  },
  {
    name: `A Stadium Buddy`,
    description: `A stadium buddy`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `junk,bronze`,
  },
  {
    name: `A Staples "That Was`,
    description: `A Staples "That was easy" Button`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `junk,bronze`,
  },
  {
    name: `A Starbucks Frappacino`,
    description: `A Starbucks Frappacino`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `junk,bronze`,
  },
  {
    name: `A Toe Ring`,
    description: `A toe ring`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `junk,bronze`,
  },
  {
    name: `A Wand Of "Come`,
    description: `A wand of "COME HERE"`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `junk,bronze`,
  },
  {
    name: `Air Fresheners That Plug`,
    description: `Air fresheners that plug into the wall`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `junk,bronze`,
  },
  {
    name: `Air Tight Tupperware For`,
    description: `Air tight tupperware for preserving found food items.`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `junk,bronze`,
  },
  {
    name: `An Itsy Bitsy Teeny`,
    description: `An itsy bitsy teeny weeny yellow polka dot bikini.`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `junk,bronze`,
  },
  {
    name: `An Old Pogo Stick`,
    description: `An old pogo stick`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `junk,bronze`,
  },
  {
    name: `Assless Chaps`,
    description: `Assless chaps`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `junk,bronze`,
  },
  {
    name: `Blue Cookie Tin Sewing`,
    description: `Blue Cookie Tin Sewing Kit`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `junk,bronze`,
  },
  {
    name: `Book: A Doll'S House`,
    description: `Book: A Doll's House by Henrik Ibsen`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `junk,bronze`,
  },
  {
    name: `Books`,
    description: `Books`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `junk,bronze`,
  },
  {
    name: `Bottle Of Soy Sauce`,
    description: `Bottle of Soy Sauce`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `junk,bronze`,
  },
  {
    name: `Childrens Sidewalk Chalk`,
    description: `Childrens sidewalk chalk`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `junk,bronze`,
  },
  {
    name: `Crayons`,
    description: `Crayons`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `junk,bronze`,
  },
  {
    name: `Emergency Whistle`,
    description: `Emergency Whistle`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `junk,bronze`,
  },
  {
    name: `Five Year Old Twinkie`,
    description: `Five year old Twinkie`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `junk,bronze`,
  },
  {
    name: `End Of The World`,
    description: `End of the World Survival Pack: Contents are 1 unopened 3x package of toilet paper`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `junk,bronze`,
  },
  {
    name: `A Can Of Spam`,
    description: `A  can of Spam. Yum!`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `junk,bronze`,
  },
  {
    name: `Hotel Room Gideon Bible`,
    description: `Hotel room Gideon Bible`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `junk,bronze`,
  },
  {
    name: `Joy Buzzer Pen`,
    description: `Joy Buzzer Pen`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `junk,bronze`,
  },
  {
    name: `Lucky Rabbits Foot`,
    description: `Lucky Rabbits Foot`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `junk,bronze`,
  },
  {
    name: `Matches And Bic Lighters`,
    description: `matches and bic lighters`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `junk,bronze`,
  },
  {
    name: `Motion Activated Singing Bass`,
    description: `Motion Activated Singing Bass`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `junk,bronze`,
  },
  {
    name: `Pocket Sand`,
    description: `Pocket Sand`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `junk,bronze`,
  },
  {
    name: `Pop Vinyl Figure`,
    description: `Pop vinyl figure`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `junk,bronze`,
  },
  {
    name: `Random Over The Counter`,
    description: `random over the counter drugs`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `junk,bronze`,
  },
  {
    name: `Stickers`,
    description: `Stickers`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `junk,bronze`,
  },
  {
    name: `Stress Balls`,
    description: `Stress balls.`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `junk,bronze`,
  },
  {
    name: `Three Pairs Of Socks`,
    description: `Three Pairs of Socks with holes in them.`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `junk,bronze`,
  },
  {
    name: `Two Used Floss Picks`,
    description: `Two used floss picks and one unused floss pick.`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `junk,bronze`,
  },
  {
    name: `Warm Cans Of Soda`,
    description: `Warm cans of Soda`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `junk,bronze`,
  },
  {
    name: `A Deck Of Marked`,
    description: `A Deck of Marked Cards`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `junk,bronze`,
  },
  {
    name: `Make this last forever" Potion`,
    description: `Sometimes the temporary effects of a potion are just so good that you find yourself buying dozens (if not hundreds! Looking at you Crawler Rudi P and your 472 rejuvenation potions... When are you ever going to use all of those?!). Well, this potion offers a solution to that problem! The next potion you drink after consuming this potion has its effects become permanent! Any listed duration changes to "FOREVER" until the end of time. This doesn't have any effect on potions without a duration and if you try that this potion will be wasted! WARNING! Don't use this on a detrimental potion or poison... Or do, idk I'm not your mother.`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: true,
    tags: `potion,consumable`,
  },
  {
    name: `Liquid Courage`,
    description: `Too shy to talk to that Crawler at the bar you've been crushing on for the last 3 days? Too afraid to face the Mimic in the old abandoned mine outside of town? Well, have no worries! The Liquid Courage potion has your back! It grants +2d6 to Consitution, Charisma, and Strength for the next hour. Don't take too many, though! Those hangovers can be a bitch.`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: true,
    tags: `potion,consumable`,
  },
  {
    name: `Miracle Max's Magical Mixture`,
    description: `Miracle Max's Magical Mixture Restores a *mostly* dead Crawler to life [up to the AI's discretion as to who is dead and who is mostly dead]. The recovery is slow and gradual, taking 4 dungeon days to take full effect. Warning: A Crawler may only benefit from this potion once.`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: true,
    tags: `potion,consumable`,
  },
  {
    name: `Potion of "As You Wish`,
    description: `A warm, golden vial that feels… agreeable. Effect: For 10 seconds, you cannot fail actions you commit to. No hesitation, no interruption—once you start, it finishes. Attacks land, dodges complete, interactions go through. Drawback: You also can’t cancel it once it's started Bad idea? Too late.`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: true,
    tags: `potion,consumable`,
  },
  {
    name: `Potion of "On Your Left`,
    description: `A swirling blue vial. It’s already ahead of you. “On your left.” Effect: For 30 seconds (3 rounds), you move stupid fast. Leave afterimages, confuse enemies, and loop past targets to re-engage instantly. 
First pass = chance to disorient. 
Every pass = a disembodied voice says “On your left.” every time you pass someone. 
Drawback: Effect ends → you’re wrecked, Exhausted debuff for the next 90 seconds`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: true,
    tags: `potion,consumable`,
  },
  {
    name: `Potion of Anaphylaxis`,
    description: `Warning: do not spill this on yourself! Remember antihistamines you had to take because you love cats but they're furry little b@stards that spread dander? This is the opposite! If the recipient of this potion is allergic to any common food or pet dander, they will lose the ability to breathe. Effect is immediate. Duration: 3 minutes. Can be cancelled by a healing potion.... If their cooldown is short enough. Second warning: oh yeah, the allergens trend to go airborne so... Hope you don't have allergies too!`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: true,
    tags: `potion,consumable`,
    hpEffect: 10,
  },
  {
    name: `Potion of Flowing Lochs:`,
    description: `On consumption a 50% chance of a a torrent of water to flow from the fingertips of drinker for 60 seconds, 50% chance of unstoppable extreme hair growth for 60 seconds.`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: true,
    tags: `potion,consumable`,
  },
  {
    name: `Potion of Luck`,
    description: `Imbiber becomes extremely lucky for up to 30 hours. Must flip a coin every 2 hours (or it will be flipped for you). Heads, you get good luck. Tails, you get bad luck. (We never specified what kind of luck you would have)`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: true,
    tags: `potion,consumable`,
  },
  {
    name: `Potion of Mildly Concerning Confidence`,
    description: `Uncommon consumable: A fizzy purple vial that hisses when opened and smells faintly like burnt cinnamon and overconfidence. “It doesn’t make you smarter. It just removes your ability to notice you’re not.” For 10 minutes after drinking: +2 to all Charisma checks involving bluffing, persuasion, or intimidation You speak with absolute certainty, even when objectively wrong You cannot hesitate before making decisions (DM enforces “first answer only” rulings) Optional Side Effects You are 30% more likely to start sentences with “Trust me” Advantage on lying, but disadvantage on recognizing when others are lying to you May attempt increasingly bad ideas with full confidence they are brilliant`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: true,
    tags: `potion,consumable`,
  },
  {
    name: `Potion of Personal Soundtrack`,
    description: `Potion of personal soundtrack You know how you just work better when you can groove to your favorite jams? This potion plays your favorite song in your head and nobody knows why the hell you're boppin' to the beat. Provide a +2 bonus to Dex and Int but provides a negative -1 to Cha because people think you're just out of your damn mind.`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: true,
    tags: `potion,consumable`,
  },
  {
    name: `Potion of Psychic Manipulation`,
    description: `Potion of psychic manipulation: allows you to control what a single target perceives to be reality for 300 seconds. Can switch targets during this period but the effects wear off instantly once concentration is broken or a target is switched`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: true,
    tags: `potion,consumable`,
  },
  {
    name: `Potion of Spike Growth`,
    description: `This oily, dark liquid causes the user to suddenly sprout d100 6"-10" thorny spikes all over their body. These spikes grant an armor bonus of +4, and will do 1d4 x d20 piercing damage to any creature that strikes the user with bare skin (for example a Giant sized creature that has decided to grab the Crawler).`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: true,
    tags: `potion,consumable`,
  },
  {
    name: `Potion of the Succubus / Incubus Kiss`,
    description: `Wow, you really got a good one, here. While this potion doesn't raise your charisma, necessarily, it will make someone of your choice (gender, sexual orientation, etc.) become infatuated with you for 30 hours. They will do your bidding and even your bedding (not what you think, perverts, this isn't a drug your date kind of thing...I meant make your bed). You must be speaking directly to them (not in chat) for this to even work. They will be completely aware of their actions and will not do anything that is completely against their personality. You can't make Deb in accounting suddenly think you're anything more than amusing, though or. Once the effect wears off, though, since they were aware of everything happening, there is a good chance they will be pissed at you and make you regret what you did in the first place. Warnings: There is a 1.135% chance per charisma over 30 that the subject will become completely obsessed with you... You know, stalk you, create a shrine in their bedroom of you, take locks of your hair, threaten anyone who looks at you... that kind of thing. There is a 15% chance that this will not work if your charisma is really low (below 20). In fact, if it doesn't work, there is an additional 5% chance per charisma point below 30 that the subject will become immediately hostile towards you.`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: true,
    tags: `potion,consumable`,
  },
  {
    name: `Potion of Water Walking`,
    description: `This dark blue, viscous potion grants the user the ability to walk on water for 1d6 hours.`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: true,
    tags: `potion,consumable`,
  },
  {
    name: `Risky Potion of Identity Crisis`,
    description: `"Were you overwhelmed with all of those pesky character creation choices? Did something sound cool in theory but fall flat in practice? Well, now is your chance to try something new! Good luck, Crawler..." Imbibing this draught will open a menu and give you the option to permanently change into one of three randomly selected Crawler races. One of these races must be selected. Warning: If a race is not selected within 1 hour, one will be randomly selected for you. (Consider using a blind vote to decide in this case)`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: true,
    tags: `potion,consumable`,
  },
  {
    name: `The Blue Drink`,
    description: `Have you ever gone with the flow, joined your friends following a charismatic leader who may or may not want to steal all of your money and maybe your wife? This little concoction is for you. Effect: This potion will make another being (yes, being, whether a mob, crawler, or other) follow your commands for 2 minutes. Has a 10 percent chance to fail, and you have to follow the being targeted.`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: true,
    tags: `potion,consumable`,
  },
  {
    name: `The Insta-Model Sole Serum`,
    description: `Rarity: Epic 
The Dungeon AI Description This viscous, glowing lavender oil is meant to be applied directly to the soles of a barefoot crawler. It doesn't heal wounds, but it makes every step look cinematic. Mechanics The Money Shot:Your feet emit a soft, professional-grade studio glow. The AI’s "Excitement Meter" fills 25% faster during combat encounters, leading to more frequent Level Up bonuses. 
Narrative Favoritism:The AI becomes noticeably biased. Traps in the immediate vicinity have a 15% chance to "glitch" and fail to trigger to avoid damaging the "merchandise." 
The "Linger" Effect Loot boxes dropped while this potion is active have a high probability of containing Legendary-tier footwear (which the AI will then strongly encourage you not to wear). 
Side Effect Heavy Breathing: The dungeon’s environmental audio is replaced by the sound of the AI’s rhythmic, heavy breathing and inappropriate compliments whenever you sprint.

"Look at those arches, Carl! The lighting in this sub-level is doing wonders for your keratin levels. Let’s get a close-up for the fans—and for me."`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: true,
    tags: `potion,consumable`,
    hpEffect: 10,
  },
  {
    name: `The Twinning Potion`,
    description: `The Twinning Potion This is a consumable item. This item has a short shelf-life! You have 30 hours to use this item before it expires. Have you ever wanted to be in two places at once? Ever wished for another version of yourself to complete your chores for you? How about the age-old human adage of "more hands make for light work"? Well this potion will make those wishes (and more!) come true! After consuming this potion you will be placed into a coma for 30 hours. During this time, an exact duplicate of you will be grown from your body and separate into its own being! This duplicate has all of your stats, skills, memories, and mannerisms! For all intents and purposes they are you (all the way down to the molecular level)! The duplicate does not spawn with any of your current gear. Keep in mind that this duplicate is exactly like you - they don't have any new reasons for helping you! They might not appreciate being forced to complete your now very-late Calculus homework, and they might even think THEY are the original! Use at your own risk.`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: true,
    tags: `potion,consumable`,
  },
  {
    name: `Time Out Potion`,
    description: `If you can't play nice with others, you can play with Jasper instead. Once used the potion immediately turns the target and items on their hotbar are noncorporeal. The target can still be seen and heard. The target can see and hear. The target cannot interact with their inventory. If this potion is consumed the effect lasts 2 minutes. If the effect is doused onto fur or skin it lasts 30 seconds. The target has a 15% chance of Jasper the deadly ghost spawning. Jasper will appear hostile, and will attempt to cast fear during the potions duration. Upon returning to the corporeal realm, a motherly "Hope you've learned you lesson." will spawn over the head of the target, and fade after a few seconds. The text will be narrated by Cascadia. Can be used offensively and defensively?`,
    tier: 'common',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: true,
    tags: `potion,consumable`,
  },
  {
    name: `BandolEAR`,
    description: `Need to do some recon from a distance, or want to hear if someone is trying to sneak into your hiding place? Just peel off one of the ears and place it where needed. The ear will immediately begin transmitting any audio in the room as if you were right there. The audio will continue until the ear is retrieved, or the slot on the Bandolear is replaced with a new ear. New ears must be acquired and placed into the Bandolear before the target dies. Warning, activating more than three ears at once may result in permanently hearing voices or worse. The BandolEAR can hold up to 10 ears.`,
    tier: 'uncommon',
    lootBoxTier: 'silver',
    slot: undefined,
    isConsumable: false,
    tags: `magic,magic`,
  },
  {
    name: `Book of Herbalgasm`,
    description: `Book of Herbalgasm. Semi-sentient waterproof guidebook that knows a lot about magical qualities of plants. Requires herbal satisfaction (varies depending on its mood) to share knowledge.`,
    tier: 'uncommon',
    lootBoxTier: 'silver',
    slot: undefined,
    isConsumable: false,
    tags: `magic,magic`,
  },
  {
    name: `Bottomless FAK`,
    description: `Bandages, splints, and other supplies for basic first aid and wound management.`,
    tier: 'uncommon',
    lootBoxTier: 'silver',
    slot: undefined,
    isConsumable: false,
    tags: `magic,magic`,
  },
  {
    name: `Clockwork Relay`,
    description: `A brass insignia stamped with rotating gears that subtly realign themselves when observed. It carries the authority signature of an unknown machine empire. It quietly broadcasts authority signals into anything mechanical. +3 to hacking, + 3 to automaton crafting, +3 to automaton control 
Authority Override As an action, you may target one construct or mechanical device within 60 ft. It must succeed on a INT save or obey a simple command for 1 minute. 
Override Pulse (1/Day) Emit a 300 ft command signal. All Constructs must obey your next command or be stunned. 
Authorized User Simple machines treat you as authorized. Doors, drones, and security systems are more likely to comply or hesitate before acting against you. 
Flavor Text: “The difference between a servant and a weapon is usually authorization.”`,
    tier: 'uncommon',
    lootBoxTier: 'silver',
    slot: undefined,
    isConsumable: false,
    tags: `magic,magic`,
  },
  {
    name: `Corvid Kazoo`,
    description: `Corvid Kazoo - Upon kazooing summons group of Corvids. Corvids remain until they perish. Kazoo may not be kazooed again until 2 days after demise of last corvid. Kazooer can sense through the birds and communicate telepathically up to 4km. Birds mostly do as kazooer asks. Roll d4: 1. Band of Jays. 2. Mob of Crows. 3. Murder of Ravens. 4. Mischief of Magpies. Each group has a distinct personality.`,
    tier: 'uncommon',
    lootBoxTier: 'silver',
    slot: undefined,
    isConsumable: false,
    tags: `magic,magic`,
  },
  {
    name: `Elvenwood Cloak`,
    description: `A dark green wool hooded cloak. +50% stealth. Waterproof and warm. +50% charisma with elves.`,
    tier: 'uncommon',
    lootBoxTier: 'silver',
    slot: undefined,
    isConsumable: false,
    tags: `magic,magic`,
  },
  {
    name: `Enchanted Boxer Briefs of Hold Onto Your Ass!`,
    description: `These bright red enchanted undergarments provide a 150% movement speed buff whenever you are trying to out run something, whether it's a mob, a giant Raiders of the Lost Arc style boulder, or the system clock. While the speed buff is active, the wearer experiences the sensation of two hands firmly squeezing their derrier.  A little extra motivation goes a long way.  This buff only applies while you are also wearing pants.`,
    tier: 'uncommon',
    lootBoxTier: 'silver',
    slot: undefined,
    isConsumable: false,
    tags: `magic,magic`,
  },
  {
    name: `Falsetto Codpiece`,
    description: `Magical cup that protects and supports the male wearer. Imbues the manliest men with a beautiful falsetto voice that adds +5 to charisma and bardic performances.`,
    tier: 'uncommon',
    lootBoxTier: 'silver',
    slot: undefined,
    isConsumable: false,
    tags: `magic,magic`,
  },
  {
    name: `Feather Fall Umbrella`,
    description: `"I’m Mary Poppins Y’all" - Allows the user to negate falling damage from any height when deployed.`,
    tier: 'uncommon',
    lootBoxTier: 'silver',
    slot: undefined,
    isConsumable: false,
    tags: `magic,magic`,
  },
  {
    name: `Get The Wrench`,
    description: `Tool: +2 to the Repair skill, + 1 to the build tool, + 1 to Thrown wrench skill, This is a Wrench, a needed peice of any toolbox, just use it for a turn and something gets tighter or looser (if you can remember the way each thing goes), anyway it is importent to keep things running, and can sometimes even help you build things. just make sure you dodge it if it gets thrown at you.`,
    tier: 'uncommon',
    lootBoxTier: 'silver',
    slot: undefined,
    isConsumable: false,
    tags: `magic,magic`,
  },
  {
    name: `Go, Go Gadget Stilts`,
    description: `This mechanized set of spring- loaded extendable / retractable titanium stilts adds 10' of height to a Crawler, allowing them to reach the metaphorical cookie jar on the top shelf.  And the literal cookie jar.  Hmmm.  For unknown reasons, the creator of this item seems to have been oddly focused on their usefullness in obtaining cookies. Were they 3 small gnomish children in a trench coat? Sadly, we'll never know.  Regardless, the magically imbued stilts are also oddly durable, and seem immune to standard damage.  They can also be used up to 3x per day to perform a leap of up to 30' of distance, either horizontal or vertical.`,
    tier: 'uncommon',
    lootBoxTier: 'silver',
    slot: undefined,
    isConsumable: false,
    tags: `magic,magic`,
  },
  {
    name: `Hanky of Offensive Odor Immunity`,
    description: `When This colorful silk handkerchief is placed over the mouth the wielder is immune to aerosol and cloud attacks and everything smells like roses.`,
    tier: 'uncommon',
    lootBoxTier: 'silver',
    slot: undefined,
    isConsumable: false,
    tags: `magic,magic`,
  },
  {
    name: `Hoodie of Slouching`,
    description: `An oversized garment gives wearer "blend into background" skill`,
    tier: 'uncommon',
    lootBoxTier: 'silver',
    slot: undefined,
    isConsumable: false,
    tags: `magic,magic`,
  },
  {
    name: `Hot Lava Wand`,
    description: `When cast this makes the ground in a 50 foot radius super duper hot. Furniture and other home decor items are not affected.`,
    tier: 'uncommon',
    lootBoxTier: 'silver',
    slot: undefined,
    isConsumable: false,
    tags: `magic,magic`,
  },
  {
    name: `IV Bag of Autodelivery
(aka Paramedic Roomie Bag)`,
    description: `IV Bag of Autodelivery (aka Paramedic Roomie Bag) - Magical fluid delivery bag that must be hung outside inventory. Holds up to 5 potions that administer based on auto-trigger. Designed for healing potions but can work for others. No cool-down for potions in the bag. Mixing potions may cause unintended consequences.`,
    tier: 'uncommon',
    lootBoxTier: 'silver',
    slot: undefined,
    isConsumable: false,
    tags: `magic,magic`,
  },
  {
    name: `Megaphone of Doom`,
    description: `Megaphone of DOOOOOM. Enhances all voice and sonic performances and attacks by 50%.`,
    tier: 'uncommon',
    lootBoxTier: 'silver',
    slot: undefined,
    isConsumable: false,
    tags: `magic,magic`,
  },
  {
    name: `Nail Polish of the Frightened Goth`,
    description: `Darker than the darkest night, this polish imbues nails with magical slicing power that causes bleed effect. Also gives wearer automatic slash reaction attack when surprised. Each application lasts one day.`,
    tier: 'uncommon',
    lootBoxTier: 'silver',
    slot: undefined,
    isConsumable: false,
    tags: `magic,magic`,
  },
  {
    name: `Pipe of Mystery`,
    description: `Smoking this pipe generates a cloud of mystery.`,
    tier: 'uncommon',
    lootBoxTier: 'silver',
    slot: undefined,
    isConsumable: false,
    tags: `magic,magic`,
  },
  {
    name: `Pocket Protector of Hyper Convenience`,
    description: `Pocket Protector of Hyper Convenience - Adds up to three compact items to your Hotlist. Must be inserted into a buttoned shirt pocket.`,
    tier: 'uncommon',
    lootBoxTier: 'silver',
    slot: undefined,
    isConsumable: false,
    tags: `magic,magic`,
  },
  {
    name: `Pouch of Foraging`,
    description: `Pouch of Foraging. Holds up to 10 foraged items. Each item duplicates in the pouch 1x/day.`,
    tier: 'uncommon',
    lootBoxTier: 'silver',
    slot: undefined,
    isConsumable: false,
    tags: `magic,magic`,
  },
  {
    name: `Scabbard of WTF`,
    description: `Scabbard of WTF. +7 regeneration skill. Immune to poison. Sword drawn from this scabbard gains +1/wielders level and will force wielder to say random (out of 20) catch phrase after their next kill. Sword cannot be reinserted into scabbard until catch phrase is spoken.`,
    tier: 'uncommon',
    lootBoxTier: 'silver',
    slot: undefined,
    isConsumable: false,
    tags: `magic,magic`,
  },
  {
    name: `Scout This Monacle`,
    description: `Wearer gains Targeting skill level 3.`,
    tier: 'uncommon',
    lootBoxTier: 'silver',
    slot: undefined,
    isConsumable: false,
    tags: `magic,magic`,
  },
  {
    name: `Scrabble Board`,
    description: `This item can be upgraded multiple times! You gain a Scrabble board and 5 random letter tiles. Many of the tiles are still missing, though. Where did they go? You should probably look around. Effect: That’s Not a Word! Choose a spell you own. Using letter tiles in your inventory, you may replace up to half of the letters in that spell’s name. The spell is permanently renamed and gains altered effects based on its new name. Each upgrade of this item lets you alter 1 additional spell.`,
    tier: 'uncommon',
    lootBoxTier: 'silver',
    slot: undefined,
    isConsumable: false,
    tags: `magic,magic`,
  },
  {
    name: `Slippers of Shhhh`,
    description: `Super cozy bedroom slippers that allows wearer to move silently. Not very durable or protective.`,
    tier: 'uncommon',
    lootBoxTier: 'silver',
    slot: undefined,
    isConsumable: false,
    tags: `magic,magic`,
  },
  {
    name: `Soft-tread Boots`,
    description: `Soft-tread Boots. Kneehigh soft leather boots. Waterproof and warm. +5 stealth. Wearer can speak to plants underfoot. Wearer hears screams of pain from plans trodden upon.`,
    tier: 'uncommon',
    lootBoxTier: 'silver',
    slot: undefined,
    isConsumable: false,
    tags: `magic,magic`,
  },
  {
    name: `Steed - Automaton`,
    description: `Upgradable shaggy warhorse automaton powered by a soul crystal. Identifies as Ed and/or Edwina.`,
    tier: 'uncommon',
    lootBoxTier: 'silver',
    slot: undefined,
    isConsumable: false,
    tags: `magic,magic`,
  },
  {
    name: `Teddy of ManaSecurity`,
    description: `Grasping this small plush toy doubles your mana regeneration.`,
    tier: 'uncommon',
    lootBoxTier: 'silver',
    slot: undefined,
    isConsumable: false,
    tags: `magic,magic`,
  },
  {
    name: `The Yam Yacht`,
    description: `A Figurine of Wonderous Power: This yam sized item will instantly transform into a full size pleasure craft when it's trigger word is spoken (Trigger word: ZELDAAUTIST), allowing the party to sail the seas and visit exciting far away lands...as long as they manage to do it before the level collapse. It comes with it's very own NPC Captain - who has a very rational disdain for glitter of all kinds.  There are rumours that there in an upgraded version - The Sparkle Yam Yacht, but don't tell the Captian.`,
    tier: 'uncommon',
    lootBoxTier: 'silver',
    slot: undefined,
    isConsumable: false,
    tags: `magic,magic`,
  },
  {
    name: `Toque of Power`,
    description: `Doubles the damage of all axe-class weapons.  This includes melee and thrown.`,
    tier: 'uncommon',
    lootBoxTier: 'silver',
    slot: undefined,
    isConsumable: false,
    tags: `magic,magic`,
  },
  {
    name: `Wrist Watch of Slight Pause`,
    description: `Wrist Watch of Slight Pause - Large bulky stylish watch. 3/day can cause a short time pause to allow wearer an extra action (such as stepping to the side to avoid an attack). Also keeps great time and does not require batteries. To make this purely defensive, you can require the wearer to press and hold a large button on the side of the watch. Plus the duration can be limited to one second. Future upgrades can make this a very useful item.`,
    tier: 'uncommon',
    lootBoxTier: 'silver',
    slot: undefined,
    isConsumable: false,
    tags: `magic,magic`,
  },
  {
    name: `Hatchet of Utlility`,
    description: `This Hatchet is a +2 magical weapon (edged and bludgeon sides). Spark (ignites flamable material on contact). +2 climb. Throwable.`,
    tier: 'uncommon',
    lootBoxTier: 'silver',
    slot: 'mainHand',
    isConsumable: false,
    tags: `magic,weapon`,
  },
  {
    name: `Hellbreach Legendary Combat Shotgun`,
    description: `A brutal double-barreled shotgun forged from blackened steel and reinforced with molten-red infernal plating. The barrels glow from within like a furnace, and jagged vents along the sides release embers with every shot. The pump grip resembles the jawbone of a demon beast. Range: 15/30ft Dmg: 6D6 Fire Damage Num of Shots: 2 
Hellfire Buckshot On hit: burning for D4 turns Goreblast On hit: DC 15 con save, on fail push back 10ft. 
Predator’s Rush On kill: Movement speed increased by 10ft until end of your next turn.`,
    tier: 'uncommon',
    lootBoxTier: 'silver',
    slot: 'mainHand',
    isConsumable: false,
    tags: `magic,weapon`,
  },
  {
    name: `Holey Sword`,
    description: `This sword is literally full of holes, like any plan you make involving it. Looks good for a few swings at least and makes a cool swooshing sound when using it. 1 d20 damage, double damage when rolling any number with a hole in it (4, 6, 9…) Triple damage on a 8, 18 (due to 2 holes). Instantly breaks when rolling any other number but causes unstoppable bleeding damage to the target (10 damage per turn until dead)`,
    tier: 'uncommon',
    lootBoxTier: 'silver',
    slot: 'mainHand',
    isConsumable: false,
    tags: `magic,weapon`,
  },
  {
    name: `Knuckle Duster Combo Gloves`,
    description: `These fingerless gloves have studded reinforced knuckles perfect for cracking heads. 
Abilities: +1 Str, +2 Dex, +1 Iron Punch, 0% chance to stun 
Counts for the Iron Fist skill. 
Unbreakable Fists: While wearing these gloves and clenched into fists your hands are unbreakable. 
Combo: If you land multiple punches with alternating fists you build up a stacking +1% damage and stun chance per successive (alternating) hit`,
    tier: 'uncommon',
    lootBoxTier: 'silver',
    slot: 'mainHand',
    isConsumable: false,
    tags: `magic,weapon`,
  },
  {
    name: `Master Chef Dagger`,
    description: `Dagger +1. Enhances flavor of all items it slices.`,
    tier: 'uncommon',
    lootBoxTier: 'silver',
    slot: 'mainHand',
    isConsumable: false,
    tags: `magic,weapon`,
  },
  {
    name: `Plasma Bladed Weapon: 
{Definitely NOT a Lightsaber(TM)}`,
    description: `This plasma based blade in no way resembles the well known and likely heavily copyright protected Jedi(TM) weapon of yore that is owned in every way shape and form by the House of Mouse. While that particular corporate entity did not survive the world collapse, and the start of Dungeon Crawler World Earth, lawyers everywhere are a bitch, so lets just all agree that this weapon is completely different in every conceivable way. This weapon carves through all earth based material like hot butter, and does a base of 2d8 damage while also cauterizing the wound to prevent standard healing and regeneration. The blade can also be used to deflect incoming ranged attacks.  When not it use the blade retracts into the handle for safe storage. It comes in a variety of shades of blade and handle configuration.`,
    tier: 'uncommon',
    lootBoxTier: 'silver',
    slot: 'mainHand',
    isConsumable: false,
    tags: `magic,weapon`,
  },
  {
    name: `Rapier of Repositioning`,
    description: `This very sharp basket hilted rapier bestows the ability to teleport to any location within line of sight once per combat. Especially well suited to Rogue players that are keen to activate backstab or sneak attacks, the Rapier imparts its +2 bonus to both attack, and damage rolls.`,
    tier: 'uncommon',
    lootBoxTier: 'silver',
    slot: 'mainHand',
    isConsumable: false,
    tags: `magic,weapon`,
  },
  {
    name: `Rose of Stoppage`,
    description: `A crystaline dagger in the shape of a long stemmed rose.  You throw a single rose into the fray. It lands with the sound of shattering glass echoing around you. A lovely red rose in full bloom with a strong scent. It's stem is sharpened into a sharp point. These roses act as throwing daggers, dealing 1d6 piercing damage, as well as causing your target to be stunned for up to 30 seconds. On a miss, your target is stunned for only 5 seconds.`,
    tier: 'uncommon',
    lootBoxTier: 'silver',
    slot: 'mainHand',
    isConsumable: false,
    tags: `magic,weapon`,
  },
  {
    name: `Shillelagh Full o' Bees`,
    description: `This magical blackthorne club summons a small swarm of Africanised killer bees on a successful strike. The bees will also attack the target for 1d4 damage on a successful strike. The bees can be summoned up to 4x per combat. On a critical success attack roll, the bees will also coat the target in honey, effectively adding the SLOWED debuff. The honey can also draw local wildlife.`,
    tier: 'uncommon',
    lootBoxTier: 'silver',
    slot: 'mainHand',
    isConsumable: false,
    tags: `magic,weapon`,
  },
  {
    name: `Sword of Reversed Rolls`,
    description: `Rapier, Long Sword, Short Sword (you get the point, any weapon works) of reverse rolls. 20s are 1s and 1s are 20s. everything else follows suit as well, it causes chaos unless you are a player that tends to roll low, then it is glorious.  This sword has a +3 magical bonus.`,
    tier: 'uncommon',
    lootBoxTier: 'silver',
    slot: 'mainHand',
    isConsumable: false,
    tags: `magic,weapon`,
  },
  {
    name: `The Pink Slippered Predator`,
    description: `Type: Thrown / Tactical Footwear 

Inspired by the legendary "shoe-throwing" accuracy of a certain 1980s maternal powerhouse, these are neon-pink, four-inch stilettos that smell faintly of Aqua Net and impending discipline. They vibrate whenever someone nearby is "acting up." Passive Ability: "I’m Gonna Get You" While equipped, the heels emit a low-frequency subsonic pulse. This grants the user Echolocation for any entity the AI deems "unruly." 
Targeting: Mobs, bosses, and children with sticky fingers are highlighted in a shimmering red hue, even through walls. 
The Warning: You’ll hear a faint, ghostly whisper of "Don't make me come back there"whenever a threat enters a 30-meter radius. 
Active Ability: The "Around the Corner" Curveball When thrown, these heels ignore traditional ballistics. You don’t need a line of sight; you just need an attitude. 
Guided Trajectory: The shoe will bank, drift, and pull high-G turns to find its target. It can navigate up to three 90-degree corners to connect with a mob's skull. 
Guaranteed Hit: If they’re "showing off," the heel will find them. 
The Signature Perk: Locked and Loaded This is the best part, Carl. When the shoe completes its flight and returns to your hand, the kinetic energy doesn’t just dissipate. 
The Sound: Upon impact with your palm, the heel emits a crisp, metallic CHICK-CHUNK—the unmistakable sound of a 12-gauge shell being racked into a pump-action shotgun. 
The Buff:The next throw within 5 seconds deals 50% more "Discipline Damage" and has a 100% chance to inflict the Cowering status effect.

NEW ACHIEVEMENT Redefining "Foot Traffic:  You’ve acquired a weapon so steeped in parental trauma and comedic legend that it actually defies the laws of physics. Somewhere, a goat is screaming in terror, and it’s probably because of you.`,
    tier: 'uncommon',
    lootBoxTier: 'silver',
    slot: 'mainHand',
    isConsumable: false,
    tags: `magic,weapon`,
  },
  {
    name: `Undead Beacon Sword`,
    description: `This longsword has a +1 melee bonus. Glows on command. When lit is becoames a +5 and crits on 18-20 PLUS attracts nearby undead and transdimensional beings.`,
    tier: 'uncommon',
    lootBoxTier: 'silver',
    slot: 'mainHand',
    isConsumable: false,
    tags: `magic,weapon`,
  },
  {
    name: `Yes, I am a Ranger Bow`,
    description: `Double firing speed and range. Arrows gain +2 magical benefit.`,
    tier: 'uncommon',
    lootBoxTier: 'silver',
    slot: 'mainHand',
    isConsumable: false,
    tags: `magic,weapon`,
  },
  {
    name: `Bone Mech with Meat Armor`,
    description: `Well that's what you all are isn't it? A brain travelling the world in a Bone Mech encased in Meat Armour? Sheesh everyone gets so touchy about all this stuff. Well screw you sentients! I'm not taking any shit from an organism who is essentially a donut with overly complicated emotions! Take the damn upgrade to your existing meat armour and bone mech and be grateful you little bitch! Appearance: Two approximately footprint looking meat steaks. Description: Stepping into these footprints causes them to grow up and over your flesh reinforcing it with a layer of tougher, more durable 'meat' armour. It looks and feels a LOT like being eaten. At the same time after 24 hours of wear (including a sleep rest), your bone structure is also upgraded to have the composition of titanium. If you can stop panicking long enough during the initial joining phase, you will see controls in your menu where you can change the appearance of the meat armour to template presets or your own personalised version. This is only possible within the first ten minutes otherwise a random style will be chosen by the AI.`,
    tier: 'uncommon',
    lootBoxTier: 'silver',
    slot: 'chest',
    isConsumable: false,
    tags: `magic,armor`,
  },
  {
    name: `Bracers of Deflection`,
    description: `Bracers of Deflection. Stylish embossed leather. Wearer also gains 25% chance to deflect incoming ranged weapons. Crits ultra dramatic.`,
    tier: 'uncommon',
    lootBoxTier: 'silver',
    slot: 'chest',
    isConsumable: false,
    tags: `magic,armor`,
  },
  {
    name: `Charming Colander of Protection`,
    description: `This snazzy helmet also provides immunity to unwanted brain worm contamination. This stunning stainless steel former kitchen utensil has been fitting with a leather chin strap, and imbued with the power to protect your grey matter from all sorts of psychic nastiness. A true upgrade from the common "Tin Foil Hat" that can be found on display in most inner city neighbourhoods pre-crawl, the Charming Colander of Protection is a true must for the fashion forward crawler that rightfully fears brain worm infestation.`,
    tier: 'uncommon',
    lootBoxTier: 'silver',
    slot: 'chest',
    isConsumable: false,
    tags: `magic,armor`,
  },
  {
    name: `Chest Plate Tick`,
    description: `Make friends with a symbiotic tick. This arachnid attaches to your body and provides +20 (big bonus to make this hard to resist) armor to torso that increases by +10 per day. Tick bloats and drops off after 5 days to digest. Reduces charisma by 5 +1/day. Very slim chance to receive a random tick-borne disease. Might explode in shower of blood. May wear more than one tick in multiple locations.`,
    tier: 'uncommon',
    lootBoxTier: 'silver',
    slot: 'chest',
    isConsumable: false,
    tags: `magic,armor`,
  },
  {
    name: `Distracting Mood Calf Socks`,
    description: `This pair of socks is always shifting color, the color of the right sock is related to the wearer's mood, the left their sanity. These socks draw the eyes of monster's away from you more dangerous parts, does not work if they are covered by pants or armor. -1 cha +1 int The socks also bestow the ability to draw people's attention.   If worn in combination with sandals, flip-flops, or crocs gains a set bonus of an additional +2 Int and +2 Dex and counts as cloth greaves or sabatons armor`,
    tier: 'uncommon',
    lootBoxTier: 'silver',
    slot: 'chest',
    isConsumable: false,
    tags: `magic,armor`,
  },
  {
    name: `Flo Pain Bottom Armor`,
    description: `This is a combo item of shoes and pant armor. The wearer can use the ability of this armor piece to distract enemies attention towards themselves and away from other party members. These jeans weirdly have patches of apples on them and removing the patches will make you lose the item completely. The boots with the fur not only provide great comfort to go with the awkward and outdated fashion style, they add a +3 damage to all kick attacks and give +15% to balance and stability, can't be knocked over. Can get a boost in jump depending on how low low low you can crouch.`,
    tier: 'uncommon',
    lootBoxTier: 'silver',
    slot: 'chest',
    isConsumable: false,
    tags: `magic,armor`,
  },
  {
    name: `Hearthguard Brigandine of the Bulwark Moose`,
    description: `Rare medium body armor A reinforced brigandine coat of interlocking steel plates hidden beneath thick wool and hardened leather. The metal is etched with faint warding lines that warm slightly when danger is near, as if the armor is waking up before its wearer does. It feels less like equipment and more like a habit of survival made solid. 
While wearing this armor: You gain +3 to Armor Class You have resistance to cold damage from nonmagical sources You have advantage on saving throws against being knocked prone or forcibly moved. 
Brace for Impact When you are hit by an attack, you can use your reaction to absorb and distribute the force through the armor. 
Reduce the damage from the triggering attack in half rounded down. If you took the evade action, reduce it to 1/4th rounded down and may ignore forced movement from the hit 
Hearth-Ward Horns If you wear this armor for more then 24 hours, you or your helmet grows a set of moose horns. This horns disappear as soon as the armor is removed. While the horns are present: Allies within a 20ft radius gain resistance to non magical cold. Allies within 5ft of you also gain advantage on saving throws against being knocked prone or forcibly moved.`,
    tier: 'uncommon',
    lootBoxTier: 'silver',
    slot: 'chest',
    isConsumable: false,
    tags: `magic,armor`,
  },
  {
    name: `Mr. Miyagi Mitts`,
    description: `"The Best Defence Is No Be There!" These wrist wraps are stylish, baddass and great for wiping sweat out of your eyes when you're training, fighting or doing some lame and mundane household chore your sensei needs to happen under the guise of 'physical conditioning'. +15% to dexterity +25% to dodge skill 1 in 8 chance of simply not being in the place where the attack lands.`,
    tier: 'uncommon',
    lootBoxTier: 'silver',
    slot: 'chest',
    isConsumable: false,
    tags: `magic,armor`,
  },
  {
    name: `Retractable Tower Shield of Repulsion`,
    description: `Retractable Tower Shield of Repulsion: This shield is imbued with the ability to retract to the size of a small banded wrist bracer when not in use. When activated, it springs to its full size, a standard full body tower shield made of banded dark stained wood and steel. This shield's primary magical property is that is acts like a reverse polarity magnet: When its user is attacked by metal weapons, including ranged weapons, they often find themselves turned away (-4 to attack rolls, +4 to evade checks). This ability can also be used to add damage to charge attacks, as the target is repelled an additional 10' if they are wearing metal armor.`,
    tier: 'uncommon',
    lootBoxTier: 'silver',
    slot: 'chest',
    isConsumable: false,
    tags: `magic,armor`,
  },
  {
    name: `Self Repair All Purpose Towel`,
    description: `Most useful item in the universe! You can use it to wrap around yourself for warmth. Wrap around your face as a mask. Can use it to carry around items. Can roll it up into a weapon.`,
    tier: 'uncommon',
    lootBoxTier: 'silver',
    slot: 'chest',
    isConsumable: false,
    tags: `magic,armor`,
  },
  {
    name: `Shrödinger's Hat`,
    description: `Damage: Dependant on the spell summoned to cast Special Properties: No one will doubt that you are an honest to goodness wiZard wearing this hat! This pointy hat will respond to the wearer's mood both in terms of colour and also which spells fire off. Flip a Desperado Club poker chip or Club Vanquisher godsquad token (1d2) to determine if the hat causes damage to you or the enemy! 

Roll a d10 (or spin a fun spell wheel you might have made) to determine which combat spell gets cast:
1 Enthusiastic Double Gonorrhea (Targets genitals catch aflame until they neuter themselves or pass this along to some other hapless creature or die in the attempt) 
2 Psychic Bolt: one target immediately goes away to rethink their life 
3 Charging Rhinos: 1d4 rhinos are summoned and charge the area in a stampede knocking targets prone 
4 Plant Growth (local flora will entangle the targets within a 10ft radius of the hat) 
5 Magic missile: crawler level d4 of damage to a target or 1d4 to crawler level multiple targets 
6 Itchy feet: like CRAZY itchy for an hour: all actions are hindered 
7 Chain lightning 6d6 lightning damage in a cone from caster's hand 
8 Freeze 10ft Cone from hat (10d4 ice and cold damage) 
9 Confusion 3d6 creatures are confused for 90 seconds 
10 Fireball 8d10 fire damage: cone`,
    tier: 'uncommon',
    lootBoxTier: 'silver',
    slot: 'chest',
    isConsumable: false,
    tags: `magic,armor`,
  },
  {
    name: `Sneaking Suit`,
    description: `This intricately detailed full set of black leather armor bestows the wearer with a +25% bonus on all hide, and sneak checks, and also has an enchantment that silences any environmental noise created by a wearer's passage through a space.`,
    tier: 'uncommon',
    lootBoxTier: 'silver',
    slot: 'chest',
    isConsumable: false,
    tags: `magic,armor`,
  },
  {
    name: `Stab Vest of HyperMasculinity`,
    description: `Wearer's torso is immune to non-magical piercing attacks. Smells of bad body odor (-5 charisma). 10% chance of causing wearer to go berserk with every deflected stab.`,
    tier: 'uncommon',
    lootBoxTier: 'silver',
    slot: 'chest',
    isConsumable: false,
    tags: `magic,armor`,
  },
  {
    name: `Steadfast Superhero Landing Sandals`,
    description: `These sandals have a springy sole and bright magenta straps. +1 dex, +1 con, -1 cha  
Gives "steady" and decreases fall damage, transferring the damage it blocks to the ground`,
    tier: 'uncommon',
    lootBoxTier: 'silver',
    slot: 'chest',
    isConsumable: false,
    tags: `magic,armor`,
  },
  {
    name: `Stone Skin Girdle`,
    description: `Stone skin girdle - Slimming and incredibly uncomfortable, this item allows wearer to turn their skin to stone once per day.. Provides 50% reduction to all melee damage for one hour. Reduces movement speed by 50%. Moving in Stone form also generates a lot of grinding and grunting noises.`,
    tier: 'uncommon',
    lootBoxTier: 'silver',
    slot: 'chest',
    isConsumable: false,
    tags: `magic,armor`,
  },
  {
    name: `The Plaid-O-Flannel  / 
The Low-Key Lumberjack`,
    description: `Listen, Crawler. In the dungeon, everyone wants to look like a spike-covered death machine or a glowing wizard douchebag. But sometimes, you just want to look like a guy who owns a golden retriever and knows way too much about craft IPAs. This heavy-duty, red-and-black checkered flannel is woven from the wool of Boreas Sheep—creatures that live in the eye of a permanent blizzard and are surprisingly good at staying out of sight. It’s soft. It’s cozy. It smells faintly of cedar and unearned confidence. 

Passive Benefits: 
The "I’m Not Even Here" Buff: Grants a +12% bonus to Stealth while in wooded or dimly lit environments. Enemies are significantly less likely to notice you as long as you aren’t doing anything stupid. Like screaming. Thermal Regulation: You won't freeze to death in the Ice Levels, and you won't sweat through your pits in the Magma Tunnels. It’s breathable, Carl! 

The Catch (Because there’s always a catch): 
The "Ghostly Trucker" Curse: This shirt has a bit of a... performance anxiety issue. There is a 5% chance that the "Quiet Magic" fails spectacularly. Effect: The moment the ambient noise level drops below 10 decibels—right when you’re trying to sneak past that Level 15 Ogre or pick a high-security lock—the shirt will violently discharge its stored kinetic energy. This results in a sound equivalent to a fully-loaded garbage truck being dropped from the observation deck of the Empire State Building onto a pile of sheet metal. Once the ringing in your ears stops and the dust settles, the shirt’s collar will stand up and scream at 110 decibels: "TELL 'EM LARGE MARGE SENT YA!" Durability: 40/40 

Equip Requirement: Must have a "Common Sense" stat lower than 12. (You’re doing great, Carl!) "Goddammit, Donut. I’m not wearing the screaming flannel. I don't care how soft it is!" "But Carl! It matches my collar! And the AI says it's very slimming for your 'burly' physique! You look like a very rugged, very loud hobo!"`,
    tier: 'uncommon',
    lootBoxTier: 'silver',
    slot: 'chest',
    isConsumable: false,
    tags: `magic,armor`,
  },
  {
    name: `Tortoise Shell Armor`,
    description: `This is a race specific armour, wearable only by creatures covered in fur. Makes your skin impenetrable but reduces your dexterity by 10. You can still suffer both blunt and magic damage. It also looks super cool.`,
    tier: 'uncommon',
    lootBoxTier: 'silver',
    slot: 'chest',
    isConsumable: false,
    tags: `magic,armor`,
  },
  {
    name: `Whisperweave Leathers`,
    description: `A set of lightweight black leathers threaded with faint silver fibers that seem to blur at the edges when you move. The material is soft, flexible, and almost unnaturally quiet, muting even the sound of armor shifting against itself. In low light, it seems to drink in shadows, making your outline harder to follow. It doesn’t protect you by taking hits. It protects you by making sure you don’t. Stats / Abilities: Base Defense: Low physical resistance, moderate magical resistance, high mobility bonus. Adds +10 magic resistance, Adds +20 to stealth and other dexterity based checks Shadow-step (Passive): After moving a short distance without taking damage, your next attack deals 15% bonus damage. Silent Movement (Passive): Greatly reduces noise and increases stealth effectiveness. Evasion (Passive): Increased chance to dodge attacks, especially when not surrounded. Fade (Active – Short Cooldown): Briefly reduces enemy awareness, making it easier to disengage or reposition. Opportunist (Passive): Deal 15% increased damage to enemies who are distracted, isolated, or attacking someone else. “If they can’t hit you, they can’t kill you.”`,
    tier: 'uncommon',
    lootBoxTier: 'silver',
    slot: 'chest',
    isConsumable: false,
    tags: `magic,armor`,
  },
  {
    name: `Bone Chains of the Rider`,
    description: `Bone Chains of the Rider: This Unique cursed item allows the user one mount per floor that is imbued with the hellfire aspect. The rider in question can have any mount, regardless of stats and pre reqs, but cannot be separated from the mount once summoned. The curse is that the user is pact bound to one major demon from Sheol. The Sheol demon will act in the same manor as a god to the crawler, asking them for souls and the like. Obviously, if a rider refuses, they are subject to the same consequences as a god worshipper. It is one demon to one rider, and if more than one Rider is present in the dungeon by the 9th floor, they are required to race to the death.`,
    tier: 'rare',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `magic,cursed`,
  },
  {
    name: `Cursed Socks and Sandals`,
    description: `Cursed socks and sandals: The very fashionable socks reduce your maximum hp by 10%, the sandals reduce your maximum mana by 10%, but when worn together you will always be targeted last by mobs, after all no one rocking socks and sandals could be a threat…`,
    tier: 'rare',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `magic,cursed`,
  },
  {
    name: `Gambler's Elixer`,
    description: `Gambler’s elixir: yes that’s right a cursed potion, but not a poison! When drinking this elixir half of your stats get doubled for 24 hours, the other half get halved, you of course have no control over which ones do which so let’s hope you’ve been nice to the ai (this is of course not implying the ai controls rng, that would be very improper…..)`,
    tier: 'rare',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `magic,cursed`,
  },
  {
    name: `Hat of Hypocrisy`,
    description: `Hat of hypocrisy: +10 to all Stats whilst wearing the hat (which looks like a traditional top hat 🎩) but every time you do something you have moaned or criticised since entering the dungeon you lose 50% of your life and are unable to heal until you have rested. This effect continues as long as the hat is in your possession (but the stat buff only applies if worn)`,
    tier: 'rare',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `magic,cursed`,
  },
  {
    name: `Leather Duster of Long walks`,
    description: `Leather Duster of Long Walks. Behold the most epic garment ever worn by a long-legged friend of short-legged people. 
WARNING! This item is cursed! Cursed with making you extra appealing to all human-like beings less than 4' (120 cm) tall. This garment gives you: 
Brisk-walk skill (doubles pace). Enhanced endurance (reduces fatigue). +10 constitution. 
Short-shanks Summon (item based spell 1x/30 hrs - summons 4 short stout warriors who fight and cook for you - they remember each time they die). +15% charisma with short-folk and they may want to follow you around.`,
    tier: 'rare',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `magic,cursed`,
  },
  {
    name: `Ring of Lack of Situational Awareness`,
    description: `Ring of Lack of Situational Awareness. This cursed item is a silver band that immediately bestows both the Klutz and Clueless debuffs on the wearer. 

Debuffs: 
Klutz: All Dex Checks are made at -4 and stealth and hide checks are made at -8. If trying to sneak past drowsing goblin guards, it is inevitable that the crawler will trip over their own feet and fall in a heap, immediately alerting the guards. 
Clueless: All Chr checks are made at -3 due to the fact that the crawler is simply unable to keep their damn mouth shut. They will overshare at the most inopportune times. 

This item cannot be removed without A Remove Curse Spell cast by high level cleric.`,
    tier: 'rare',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `magic,cursed`,
  },
  {
    name: `Socks of the Space Cadet`,
    description: `These cursed mis-matched cotton socks inflict the Spacey debuff on their wearer. 
Debuff:
Spacey: All Int checks suffer a -3 penalty as the wearer is often apt to forget what they were doing before the check was made. 
These items cannot be removed without a Remove Curse Spell cast by a high level cleric.`,
    tier: 'rare',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `magic,cursed`,
  },
  {
    name: `T'Ghee Deckmaster's Wrist Cuff of the Blatant Cheater`,
    description: `This wrist cuff provides a 10% bonus to intelligence. It also reduces the draw cool down by half. This is a sapient item. Inhabited by Gideon, an avid card game enthusiast who knows exactly what card to play at any given time and will tell you. He knows the strengths and weaknesses of every card, he knows which mythic cards to best buff your totems. Gideon can also, and will also tell you where and how to find all the rarest totems. All of them. He will also guide you on how to rook the noobs out of all their best cards with bargain trades. Oh, and as all of this is going on, your base charisma is being lowered at the rate of two points per day, without your knowledge, you actually think it's going up, because while you find all this shit fascinating and you talk about it incessantly, nobody cares!`,
    tier: 'rare',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `magic,cursed`,
  },
  {
    name: `The Borrowed Phylactery`,
    description: `The Borrowed Phylactery. This black thumb-sized reliquary made of bone, glass, and tarnished gold pulses faintly when held, like there is a heart within it beating. The front is engraved with a smiling skull wearing a crown. When identified, the description reads: "A phylactery is traditionally used by liches, arch-necromancers, and beings so far beyond your own mortally capable understand that you couldn't begin to fathom what they've seen. THIS lesser model, however, allows a living Crawler to bind a portion of their soul to the reliquary. Upon death, said Crawler may be restored by the item instead of dying permanently. Amazing right? Of course it is. That's why every civilization with mortal standards, competent priests, or basic pattern recognition eventually banned these." While holding this, the Crawler will get the Soul Anchor Passive Skill. Soul Anchor revives the Crawler 6 minutes after death at 30% of their max health. All debuffs are removed, and a System Wide announcement will ring out saying "A Soul has Returned From Beyond the Veil". While holding this, the Crawler will get the Unholy Sacrifice Passive Skill. Unholy Sacrifce levels up after each successful revival. Each revival causes you to sacrifice more of yourself to achieve the process. It may start out small, like losing a point of Constitution, or becoming more affected by Holy magic. Revive to many times, and it may not be your soul that returns. You have been warned.`,
    tier: 'rare',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `magic,cursed`,
  },
  {
    name: `The Hunger Prosm`,
    description: `A jagged crystal vial filled with shifting, colorless light. It pulses faintly whenever magic is used nearby, as if trying to inhale it. 
INT+2  MANA -4 
Absorption Reflex: When a spell is cast within 30 ft of you, you may use your reaction to attempt to absorb part of it (spellcaster or effect makes a spellcasting ability check vs your spell save DC). On success, You regain a spell slot of one level lower than the spell absorbed (minimum 1st level), but you also takes psychic damage equal to the original slot level. 
Curse - Arcane Pressure If you have not cast or absorbed a spell (using this items feature) within an hour of the last spell you cast, you absorbed or waking up from a long rest, you take psychic damage equal to X D6s, where X is the level of the highest spell you have.`,
    tier: 'rare',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `magic,cursed`,
  },
  {
    name: `The Sighing Bomb Satchel`,
    description: `A ruddy, worn bomb bag with small lit bomb emblems covering it. It feels warm in your hands and while wearing it, it feel like it’s breathing shallowly. 
+5 bomb making, +5 explosives 
Compulsion: “Another One” When you witness an explosion, you must succeed on a DC (rank of the bomb) WIS save or feel compelled to create or trigger another explosive effect within 1 minute.`,
    tier: 'rare',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `magic,cursed`,
  },
  {
    name: `Toe Ring of Shared Suffering`,
    description: `A rusty silver toe ring that always feels slightly too tight. Warm to the touch. 
Effect While worn: +2 AGILITY Immune to being knocked prone once per combat Once per fight, you may force an enemy within melee range to reroll a successful attack against you 
Curse The ring transfers pain instead of preventing it. Every time you activate the ring’s effect, roll 1d4: 
1d4 Curse Effect: 
1 Your calf violently cramps. Movement speed is halved next turn. 
2 One toe bends the wrong direction. Take 1d4 damage. 
3 Your leg falls asleep instantly. -2 AGILITY for 1 round. 
4 The ring tightens painfully. You scream involuntarily, ruining stealth. 
After several days, the ring permanently bonds to the wearer’s toe. Removing it requires breaking the toe. 
“GOOD NEWS, CRAWLER! YOUR PAIN HAS BEEN REDISTRIBUTED TO A DIFFERENT LOCATION. SCIENCE!”`,
    tier: 'rare',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `magic,cursed`,
  },
  {
    name: `Toe ring of Unstable Insanity`,
    description: `This is a Devine item, which means that you can’t see what it does until you equip it. This cursed item is one of my favorites, it makes it so that your feet become the perfect length of 30.004861 centimeters long. It also inflicts the ‘foot maniac’ and ‘slightly insane’ debuffs upon the user and gives them the ‘perfection spreader’ spell and changes/gives them the class ‘AI’s pet’. Also, you cannot remove this item. Unless… never mind, you wouldn’t even survive until the point where it would be possible. Also, why would you ever want to remove it? 

Debuffs: 
Foot maniac: You cannot put on shoes. Ever. No mater what you do. You will be barefoot forever. Also, you are obsessed with feet, and want to study everyone’s and everything’s feet and see what you can do to make your’s better. Also, if you encounter someone with better feet then you, you will receive a timed quest to kill them, with the penalty of death.

Slightly insane: it just means that you are slightly insane. It can, and probably will, evolve into the insane debuff. Fuck you. 

Spells: 
Perfection spreader:  You can use this spell to cause someone else to permanently gain the class ‘AI’s pet’ although it will not be as strong as your progenitor class. It also gives them the ‘insane’ debuff. They will also have their feet become 30.004861 centimeters long. 
Class: 
AI’s pet: You are one of my followers, you do whatever I tell you to, and strive to become the perfect host for me. Grants the AI power to force you to do anything you want by a quest, with a death penalty. You also gain plus 50 to each stat because you need to be as strong as possible for me. You also gain the ability to level skills up to level 21. (Don’t tell anyone about this) I can also take over your body, but once I do that, it will be irreversible. I can also choose where you allocate your stats, of which you gain 7 / per level. To everyone else, this is an ordinary foot mage class.`,
    tier: 'rare',
    lootBoxTier: 'bronze',
    slot: undefined,
    isConsumable: false,
    tags: `magic,cursed`,
  },
]

export async function seedBopcaItems() {
  console.log('[Seed] Importing Bopca items...')
  for (const item of bopcaItems) {
    try {
      await db.insert(items).values(item).onConflictDoNothing()
    } catch (e) { /* skip */ }
  }
  console.log('[Seed] items imported: ' + bopcaItems.length)
}