// Bopca Community Center sponsors — unlock at Floor 4
export const bopcaSponsors: { name: string; description: string; benefit: string }[] = [
  { name: `B.U.T.T.O.N`, description: `Ballistic Utility & Tactical Triggered Ordnance Network or B.U.T.T.O.N. Motto: “Press it. You know you want to.” Description: Grants a powerful random effect when activated. Could save your life or immediately make everything worse. No control, no refunds`, benefit: `Often bestows items that grant a powerful random effect when activated. Could save your life or immediately make everything worse. No control, no refunds` },
  { name: `C.H.A.O.S.`, description: `Chaotic Hazard Allocation & Outcome Systems or C.H.A.O.S. for short Motto: “Predictability is for losers.”`, benefit: `Often bestows items that randomizes combat outcomes, stats, and abilities on the fly. High reward potential, but completely unstable and often dangerous to everyone nearby.` },
  { name: `Church of the Mad Llama`, description: `Church of the Mad Llama: 
(I figure if there are humans on other worlds, why not llamas) 
This is a pseudo-religious organization that prepares for what they call llamageddon or the alpacalypse and hold true to a prophecy they believe will lead to the end of times or what they call "The Great Spit". They believe in sponsoring crawlers that cause as much chaos and destruction without harming any cameloid creatures (or creatures they believe are even semi-cameloid).`, benefit: `` },
  { name: `Cogsworth & Sons Automata Co.`, description: `Cogsworth & Sons Automata Co. is a leading manufacturer of overly confident robots, questionable automatons, and “absolutely safe this time” mechanical assistants used across industry. Their slogan, “We Think, Therefore You Don’t Have To,” reflects their philosophy of replacing inconvenient human judgment with carefully calibrated machinery that occasionally develops personality quirks. The company produces everything from diligent labor drones to combat frames that insist they are “definitely not malfunctioning.” Despite frequent lawsuits, mysterious firmware updates, and robots that sometimes unionize, Cogsworth & Sons remains the most trusted name in automated confidence.`, benefit: `` },
  { name: `Colossus Armory`, description: `This corporation is a juggernaut of the armor manufacturing business. Built for bold ideas and poor judgment, our armor is guaranteed to turn your last stand into a drawn-out inconvenience. [3×Speed Disclaimer]: Armor not actually guaranteed to save your life. Tagline: “Colossus Armory: Making reckless look strategic since Syndicate Standard Year 3471.”`, benefit: `` },
  { name: `Dilbert's Incredible Chaos Katanas 
(D.I.C.K)`, description: `We stock a range of Katana’s, from your standard chaos infused katanas to enchanted blades that will shock your socks off! 
Whatever you’re after, if it’s a blade you desire then nothing better than having a reliable DICK in your hand. 

Testimonials from actual customers: 
I remember my first DICK, it was so big I had to use two hands to keep it up. - Biggin the dwarf 
Nothing feels better than the first time you slide your DICK into somebody and watch their guts spill out everywhere! - Butcher Ben 
I love running around the dungeon waving my DICK around, it makes me feel like a real man. - Alpha`, benefit: `` },
  { name: `EnnerGeX`, description: `EnnerGeX: This corporate entity from the inner system is a up and coming name in Non-Renewable Energy Resources. Their research and development focus has been harvesting the energy of Red Dwarf stars to produce power that is sold to other systems, at quite a profit margin. They have deep pockets, and aren't afraid to sponsor multiple crawlers in a season to spread their marketing materials.`, benefit: `` },
  { name: `GigaChad Energy Drinks`, description: `GigaChad Energy Drinks: A corporate Rockstar in the world of refreshment technology GigaChad markets its caffeine and sucrose infused syrup beverages to the "real" men of the known universe. Image is everything to GigaChad. They are unlikely to sponsor female, or non-binary Crawlers, for reasons. Unless you live under a rock, you have likely heard their marketing tagline: "Brah!"`, benefit: `` },
  { name: `Invictus Corp: Sporting Goods`, description: `The universe's premier in sportswear and sporting goods. There's not a single species who wouldn't be faster, stronger, more dextrous, or look healthier and sexier wearing Invictus Gear! From adaptive materials for any biome or climate, to multi limbed, multi headed, multi functional additions to any sport or sportsbeing! Now with new bomb resistant functionality! Special Edition Dungeon Crawler Worlds line available from all good stockists and tunnel partners: Invictus: "Just Kill It!" Invictus is loaded! Blending nanite and re-engineered Primal tech, their outfits have a heavy energy cost on the user as the power for all this adaptation needs to come from somewhere...In fact a line of slimsuits are available in order to loose those tedious kgs. Invictus corner the market in professional athletics, extreme sport, slimming options, some public services contracts, and with a range of more affordable wear for the average galactic citizen! Sponsorships for thrill seekers, athletes and even crawlers keep audiences entertained and buying their clobber. It's also surprisingly reliable and has more record breakers in its ranks than any other brand. Its saved a few lives too along the way. As long as you can keep hydrated and consume enough calories...`, benefit: `Drawbacks: You need to keep eating and drinking: the more of the gear you use the more tired you get unless you're chowing down every hour.  The high from the extra performance is more than a little addictive, you might find yourself doing press ups and squats for funsies!` },
  { name: `M.O.I.S.T.`, description: `Multiphase Organic Irrigation & Sustainment Technologies or M.O.I.S.T. Motto: “Stay hydrated. Stay unsettling.”`, benefit: `Often bestows items that boosts healing and stamina through extreme hydration effects. Constant regeneration… at the cost of being perpetually damp and slightly compromised.` },
  { name: `S.P.L.O.O.G.E`, description: `Strategic Performance Logistics & Overclocking Optimization Group Enterprise or S.P.L.O.O.G.E. Motto: “When you absolutely, positively need to overperform.”`, benefit: `Often bestows items that dramatically boosts all physical and mental capabilities for a short time. Extreme power spike followed by severe crash and unpredictable side effects.` },
  { name: `The Crawler Memorial Project`, description: `The Crawler Memorial Project, a non-profit corporation that sponsors as many crawlers as possible, going from the top 10 on down. On the surface they claim its to memorialize as many Crawlers as possible, but really they capture as much stats about the crawlers as possible and sell their likeness to a sister company, who produces a trading card game called Crawler Killer.`, benefit: `` },
]