import { db } from './client.js'
import { items } from './schema.js'

const TIER2_ITEMS = [
  // ══════════════════════════════════════════════════════════════
  // GOLD TIER — Floor 2-3 drops, meaningful power spikes
  // ══════════════════════════════════════════════════════════════

  // Weapons
  { name: 'Gravity Hammer', description: 'A sledgehammer enchanted to hit like it weighs considerably more than it does. The dungeon respects commitment to the bit.', tier: 'rare', lootBoxTier: 'gold', slot: 'mainHand', effortType: 'weapon', skillBonus: '+4 to Bashing Weapons Skill', floorFound: 2, isConsumable: false, hpEffect: null, mpEffect: null, tags: 'weapon,magic' },
  { name: 'Twin Fangs (Matched Daggers)', description: 'Paired short blades from a dead crawler who made it to Floor 4. They are here, in a Floor 2 box. He did not.', tier: 'rare', lootBoxTier: 'gold', slot: 'mainHand', effortType: 'weapon', skillBonus: '+3 to Edged Weapons, attack twice per round', floorFound: 2, isConsumable: false, hpEffect: null, mpEffect: null, tags: 'weapon,dual' },
  { name: 'Sawn-Off Dungeon Shotgun', description: 'The dungeon added firearms at some point. Nobody asked. It is horrifyingly effective.', tier: 'rare', lootBoxTier: 'gold', slot: 'mainHand', effortType: 'weapon', skillBonus: '+4 to Ranged Weapons, hits all targets in cone', floorFound: 2, isConsumable: false, hpEffect: null, mpEffect: null, tags: 'weapon,ranged,firearm' },
  { name: 'Reach Spear of the Fallen Guard', description: 'Standard issue for dungeon guard corps. This one is available because the guard is not.', tier: 'rare', lootBoxTier: 'gold', slot: 'mainHand', effortType: 'weapon', skillBonus: '+3 to Reach Weapons, first strike advantage', floorFound: 2, isConsumable: false, hpEffect: null, mpEffect: null, tags: 'weapon' },
  { name: 'Cursed Berserker Axe', description: 'Increases damage dramatically. Also increases aggression. You will not be able to stop attacking until something stops moving. Choose targets carefully.', tier: 'rare', lootBoxTier: 'gold', slot: 'mainHand', effortType: 'weapon', skillBonus: '+5 to all weapon attacks, cannot disengage once combat starts', floorFound: 3, isConsumable: false, hpEffect: null, mpEffect: null, tags: 'weapon,cursed' },
  { name: 'Crossbow of Repeating Annoyance', description: 'Fires three bolts per action. Each individually underwhelming. Together, extremely rude.', tier: 'rare', lootBoxTier: 'gold', slot: 'mainHand', effortType: 'weapon', skillBonus: '+2 Ranged, fires 3 bolts per action', floorFound: 2, isConsumable: false, hpEffect: null, mpEffect: null, tags: 'weapon,ranged' },

  // Armor
  { name: 'Dungeon Warden Plate (Partial)', description: 'Standard warden-grade chest plate. Whoever wore this last did not need it anymore. Their loss is aggressively your gain.', tier: 'rare', lootBoxTier: 'gold', slot: 'chest', effortType: null, skillBonus: '+3 to CON, reduces incoming physical damage', floorFound: 2, isConsumable: false, hpEffect: null, mpEffect: null, tags: 'armor,heavy' },
  { name: 'Shadowweave Cloak', description: 'Woven from compressed shadow. Makes you harder to see in dim light. Also makes you dramatically more interesting at parties.', tier: 'rare', lootBoxTier: 'gold', slot: 'chest', effortType: null, skillBonus: '+4 to Stealth Skill', floorFound: 2, isConsumable: false, hpEffect: null, mpEffect: null, tags: 'armor,magic,stealth' },
  { name: 'Reactive Shield Bracer', description: 'Generates a brief kinetic shield on impact. Does not prevent all damage. Prevents enough damage.', tier: 'rare', lootBoxTier: 'gold', slot: 'arms', effortType: null, skillBonus: 'Blocks first hit each combat for free', floorFound: 2, isConsumable: false, hpEffect: null, mpEffect: null, tags: 'armor,magic,shield' },
  { name: 'Boots of the Relentless', description: 'Move 10 extra feet per action. Cannot be slowed by difficult terrain. The dungeon hates how fast you are.', tier: 'rare', lootBoxTier: 'gold', slot: 'feet', effortType: null, skillBonus: '+10ft movement, ignore difficult terrain', floorFound: 2, isConsumable: false, hpEffect: null, mpEffect: null, tags: 'armor,magic' },
  { name: 'Crown of the Audience Favourite', description: 'A circlet that glows brighter as your viewer count increases. Maximum glow achieved at 10 million viewers. You are nowhere near that. Keep trying.', tier: 'rare', lootBoxTier: 'gold', slot: 'head', effortType: null, skillBonus: '+3 CHA, viewer count grows 20% faster', floorFound: 2, isConsumable: false, hpEffect: null, mpEffect: null, tags: 'armor,fame,magic' },

  // Jewelry
  { name: 'Ring of the Pack', description: 'Grants a faint awareness of nearby allies. You always know roughly where they are. You do not always know if they are alive.', tier: 'rare', lootBoxTier: 'gold', slot: 'fingers', effortType: null, skillBonus: 'Sense allied positions within 60ft', floorFound: 2, isConsumable: false, hpEffect: null, mpEffect: null, tags: 'jewelry,magic,utility' },
  { name: 'Amulet of Second Wind', description: 'Once per day, when you would drop to zero HP, you instead drop to 1 HP. The audience goes absolutely feral.', tier: 'rare', lootBoxTier: 'gold', slot: 'neck', effortType: null, skillBonus: 'Once per rest: survive lethal damage at 1 HP', floorFound: 2, isConsumable: false, hpEffect: null, mpEffect: null, tags: 'jewelry,magic' },
  { name: 'Signet of the Crawler Union', description: 'Technically grants you negotiating rights with certain dungeon factions. Technically.', tier: 'rare', lootBoxTier: 'gold', slot: 'fingers', effortType: null, skillBonus: '+3 to Negotiation, hostile faction members hesitate', floorFound: 2, isConsumable: false, hpEffect: null, mpEffect: null, tags: 'jewelry,social' },

  // Consumables
  { name: 'Combat Stim (Military Grade)', description: 'One round of perfect focus. Reaction time doubles. Accuracy improves dramatically. You will absolutely crash afterwards.', tier: 'rare', lootBoxTier: 'gold', slot: null, effortType: null, skillBonus: '+5 to all combat skills for 1 round, then -2 for 2 rounds', floorFound: 2, isConsumable: true, hpEffect: null, mpEffect: null, tags: 'consumable,tactical' },
  { name: 'Large Healing Potion', description: 'Restores significant HP. Red, thick, tastes of iron and something you choose not to identify. Works though.', tier: 'rare', lootBoxTier: 'gold', slot: null, effortType: null, skillBonus: null, floorFound: 2, isConsumable: true, hpEffect: 15, mpEffect: null, tags: 'consumable,potion' },
  { name: 'Mana Surge Flask', description: 'Floods your MP reserves instantly. Side effects include mild nosebleeds and a faint smell of ozone.', tier: 'rare', lootBoxTier: 'gold', slot: null, effortType: null, skillBonus: null, floorFound: 2, isConsumable: true, hpEffect: null, mpEffect: 12, tags: 'consumable,potion,magic' },
  { name: 'Flashbang Rune', description: 'Etched on a ceramic disc. Throw. Blind everything in 15ft for one round. Including yourself, if you are not careful.', tier: 'rare', lootBoxTier: 'gold', slot: null, effortType: null, skillBonus: null, floorFound: 2, isConsumable: true, hpEffect: null, mpEffect: null, tags: 'consumable,tactical' },
  { name: 'Scroll of Haste', description: 'Doubles your actions for one round. The System does not recommend doing this near fragile things.', tier: 'rare', lootBoxTier: 'gold', slot: null, effortType: 'magic', skillBonus: 'Double actions for 1 round', floorFound: 2, isConsumable: true, hpEffect: null, mpEffect: null, tags: 'consumable,magic,scroll' },
  { name: 'Antidote (Broad Spectrum)', description: 'Clears most poisons and venom effects currently active. Does not prevent future poisonings. You will need to try harder.', tier: 'uncommon', lootBoxTier: 'gold', slot: null, effortType: null, skillBonus: 'Removes all active poison/venom effects', floorFound: 1, isConsumable: true, hpEffect: null, mpEffect: null, tags: 'consumable,potion,utility' },

  // ══════════════════════════════════════════════════════════════
  // PLATINUM TIER — Floor 3+ drops, serious power
  // ══════════════════════════════════════════════════════════════

  { name: 'Void Fang Katana', description: 'Forged in a pocket dimension by someone who had a lot of time and strong opinions about swords. Cuts through conventional armor like a social obligation through Vance.', tier: 'legendary', lootBoxTier: 'platinum', slot: 'mainHand', effortType: 'weapon', skillBonus: '+6 to Edged Weapons, ignores standard armor', floorFound: 3, isConsumable: false, hpEffect: null, mpEffect: null, tags: 'weapon,magic,void' },
  { name: 'Cannon Fist Gauntlet (Right)', description: 'The right hand counterpart to the Golem Fist. Together they are absurd. Separately they are merely alarming.', tier: 'legendary', lootBoxTier: 'platinum', slot: 'hands', effortType: 'weapon', skillBonus: '+6 to Unarmed Combat, once per combat: ranged fist cannon attack', floorFound: 3, isConsumable: false, hpEffect: null, mpEffect: null, tags: 'weapon,mechanical' },
  { name: 'Sniper Configuration Rifle', description: 'Breaks down into a case that fits in a backpack. Assembles in 6 seconds. Accurate to 300ft indoors. The dungeon architects are disturbed by the implications.', tier: 'legendary', lootBoxTier: 'platinum', slot: 'mainHand', effortType: 'weapon', skillBonus: '+6 Ranged, can target weak points for double damage', floorFound: 3, isConsumable: false, hpEffect: null, mpEffect: null, tags: 'weapon,ranged,firearm' },
  { name: 'Staff of the Dungeon Architect', description: 'Stolen from an Architect. They are not pleased. You should not stay in one room too long.', tier: 'legendary', lootBoxTier: 'platinum', slot: 'mainHand', effortType: 'magic', skillBonus: '+6 to all magic skills, can reshape minor dungeon features', floorFound: 3, isConsumable: false, hpEffect: null, mpEffect: null, tags: 'weapon,magic,utility' },
  { name: 'Chainsaw (Dungeon Modified)', description: 'A standard chainsaw fitted with dungeon-grade enchantments that keep it running indefinitely and make it supernaturally quiet. Neither of these things make it less terrifying.', tier: 'legendary', lootBoxTier: 'platinum', slot: 'mainHand', effortType: 'weapon', skillBonus: '+5 to Bashing/Edged, cleaves through multiple enemies', floorFound: 3, isConsumable: false, hpEffect: null, mpEffect: null, tags: 'weapon,mechanical' },

  // Armor
  { name: 'Exo-Frame Chassis (Partial)', description: 'A lightweight mechanical exoskeleton torso. Someone was building a full set. You have one third of it. Still transforms your survivability.', tier: 'legendary', lootBoxTier: 'platinum', slot: 'chest', effortType: null, skillBonus: '+5 CON, +3 STR, physical damage reduced by 3', floorFound: 3, isConsumable: false, hpEffect: null, mpEffect: null, tags: 'armor,mechanical,heavy' },
  { name: 'Veil of the Ghost Crawler', description: 'A full-body suit that blurs your outline to the point of near-invisibility when stationary. Crawlers who obtained this tended to disappear. Whether that was the suit or something else is unclear.', tier: 'legendary', lootBoxTier: 'platinum', slot: 'chest', effortType: null, skillBonus: '+6 Stealth, near-invisible when still', floorFound: 3, isConsumable: false, hpEffect: null, mpEffect: null, tags: 'armor,magic,stealth' },
  { name: 'Warden Commander Helm', description: 'The helmet of a Dungeon Warden Commander. It has a small dent in the right temple. The previous owner no longer requires a helmet.', tier: 'legendary', lootBoxTier: 'platinum', slot: 'head', effortType: null, skillBonus: '+4 INT, +3 CON, tactical overlay of visible area', floorFound: 3, isConsumable: false, hpEffect: null, mpEffect: null, tags: 'armor,heavy,tactical' },
  { name: 'Boots of Dimensional Stride', description: 'Each step can cross up to 10ft of impossible terrain — walls, chasms, other people. One step per round. The dungeon has lodged a formal complaint.', tier: 'legendary', lootBoxTier: 'platinum', slot: 'feet', effortType: null, skillBonus: 'Once per round: teleport up to 10ft ignoring obstacles', floorFound: 3, isConsumable: false, hpEffect: null, mpEffect: null, tags: 'armor,magic' },

  // Jewelry
  { name: 'Ouroboros Band', description: 'A ring that loops back on itself in a way that should be geometrically impossible. When you die wearing this, you return at 25% HP. Once. The ring cracks afterwards.', tier: 'legendary', lootBoxTier: 'platinum', slot: 'fingers', effortType: null, skillBonus: 'One-time death prevention: return at 25% HP (ring destroyed)', floorFound: 3, isConsumable: false, hpEffect: null, mpEffect: null, tags: 'jewelry,magic,legendary' },
  { name: 'Necklace of the Million Viewers', description: 'Worn by exactly one crawler in recorded dungeon history. She made it to Floor 9. The necklace was recovered. She was not.', tier: 'legendary', lootBoxTier: 'platinum', slot: 'neck', effortType: null, skillBonus: '+5 CHA, viewer count x3, sponsors approach you', floorFound: 3, isConsumable: false, hpEffect: null, mpEffect: null, tags: 'jewelry,fame,magic' },
  { name: 'Twin Rings of the Bonded Pair', description: 'Two rings sold together. If two crawlers each wear one, they share a faint telepathic link and split incoming damage 60/40. The System does not specify which one gets 60.', tier: 'legendary', lootBoxTier: 'platinum', slot: 'fingers', effortType: null, skillBonus: 'Paired: telepathic link + damage sharing with bonded wearer', floorFound: 3, isConsumable: false, hpEffect: null, mpEffect: null, tags: 'jewelry,magic,paired' },

  // Consumables
  { name: 'Phoenix Draught', description: 'Full HP restoration. Removes all negative status effects. Tastes like the last good decision you ever made. Single use.', tier: 'legendary', lootBoxTier: 'platinum', slot: null, effortType: null, skillBonus: 'Full HP restore, clears all debuffs', floorFound: 3, isConsumable: true, hpEffect: 999, mpEffect: null, tags: 'consumable,potion,legendary' },
  { name: 'Temporal Grenade', description: 'Slows time in a 20ft radius for 2 rounds. Everything in the radius acts at half speed. You do not. The audience cannot follow what is happening. They love it.', tier: 'legendary', lootBoxTier: 'platinum', slot: null, effortType: null, skillBonus: '20ft slow zone: all others at half speed for 2 rounds', floorFound: 3, isConsumable: true, hpEffect: null, mpEffect: null, tags: 'consumable,tactical,magic' },
  { name: 'Scroll of the Architect Override', description: 'Rewrite one room rule for the current room. One use. The Architects will send someone to investigate. They take 1d6 rooms to arrive.', tier: 'legendary', lootBoxTier: 'platinum', slot: null, effortType: 'magic', skillBonus: 'Rewrite one current-room rule (GM discretion)', floorFound: 3, isConsumable: true, hpEffect: null, mpEffect: null, tags: 'consumable,magic,scroll,legendary' },

  // ══════════════════════════════════════════════════════════════
  // LEGENDARY TIER — Endgame, campaign-defining items
  // ══════════════════════════════════════════════════════════════

  { name: 'The Dungeon\'s Own Sword', description: 'A weapon the dungeon itself forged and lost. It remembers every room it has passed through. It wants to pass through more. It does not distinguish between friend and enemy. That is your problem, not its.', tier: 'legendary', lootBoxTier: 'legendary', slot: 'mainHand', effortType: 'weapon', skillBonus: '+8 all weapon skills, sentient: chooses targets on a crit', floorFound: 3, isConsumable: false, hpEffect: null, mpEffect: null, tags: 'weapon,magic,sentient,legendary' },
  { name: 'Mantle of the Undying', description: 'A cloak that has passed through the deaths of seven previous wearers. It carries their echoes. Sometimes they help. Sometimes they argue. Always they are present.', tier: 'legendary', lootBoxTier: 'legendary', slot: 'chest', effortType: null, skillBonus: '+6 CON, max HP +30, death save advantage', floorFound: 3, isConsumable: false, hpEffect: null, mpEffect: null, tags: 'armor,magic,legendary' },
  { name: 'Crown of the Dungeon King', description: 'There has not been a Dungeon King in 200 years. Wearing this makes various factions very uncomfortable. Some will try to kill you. Others will try to serve you. Both are inconvenient.', tier: 'legendary', lootBoxTier: 'legendary', slot: 'head', effortType: null, skillBonus: '+6 CHA, command dungeon-aligned creatures, faction reactions shift dramatically', floorFound: 3, isConsumable: false, hpEffect: null, mpEffect: null, tags: 'armor,magic,legendary,social' },
  { name: 'Gauntlets of the First Crawler', description: 'Worn by the first person to enter the dungeon voluntarily. They made it to Floor 10. The dungeon keeps these as a trophy. You found them anyway. Good luck.', tier: 'legendary', lootBoxTier: 'legendary', slot: 'hands', effortType: 'weapon', skillBonus: '+7 Unarmed, all combat skills +2, STR +4', floorFound: 3, isConsumable: false, hpEffect: null, mpEffect: null, tags: 'armor,weapon,magic,legendary' },
  { name: 'The Contractor\'s Ledger', description: 'A small book containing the names of every crawler who has signed a dungeon contract. Adding your own name does something. The System declines to say what.', tier: 'legendary', lootBoxTier: 'legendary', slot: null, effortType: null, skillBonus: 'Unknown effects. GM discretion. Handle carefully.', floorFound: 3, isConsumable: false, hpEffect: null, mpEffect: null, tags: 'utility,magic,legendary,mystery' },
  { name: 'Void Heart Gem', description: 'A gemstone that pulses with a slow, rhythmic beat entirely out of sync with your own. Embedding it in any weapon or armor creates a legendary-tier enhancement. The embedding process is painful. Irreversible.', tier: 'legendary', lootBoxTier: 'legendary', slot: null, effortType: null, skillBonus: 'Embed in any item: grants it legendary status and +3 to its primary stat', floorFound: 3, isConsumable: true, hpEffect: null, mpEffect: null, tags: 'utility,magic,legendary,upgrade' },

  // ══════════════════════════════════════════════════════════════
  // CELESTIAL TIER — Mythic, one-per-campaign type drops
  // ══════════════════════════════════════════════════════════════

  { name: 'The System\'s Apology', description: 'A letter, materialised in a loot box, written by the System itself. It contains a formal apology for placing you in this situation and a coupon for 20% off any dungeon shop purchase. The coupon is genuine. The apology is debatable.', tier: 'legendary', lootBoxTier: 'celestial', slot: null, effortType: null, skillBonus: '20% dungeon shop discount, +5 to all stats for one encounter', floorFound: 3, isConsumable: true, hpEffect: null, mpEffect: null, tags: 'utility,legendary,celestial,mystery' },
  { name: 'Architect\'s Blueprint (Partial)', description: 'A schematic for a section of the dungeon that has not been built yet. Holding it gives you foreknowledge of one future room. The dungeon does not appreciate you having this.', tier: 'legendary', lootBoxTier: 'celestial', slot: null, effortType: null, skillBonus: 'Reveal full details of one upcoming room (GM describes it now)', floorFound: 3, isConsumable: true, hpEffect: null, mpEffect: null, tags: 'utility,legendary,celestial,intelligence' },
  { name: 'Floor Key — Early Descent', description: 'Opens the floor descent portal from any room, bypassing the room count requirement. The System notes that early descent carries consequences. The System does not elaborate. The System is being passive aggressive.', tier: 'legendary', lootBoxTier: 'celestial', slot: null, effortType: null, skillBonus: 'Immediately descend to next floor from any room (stasis penalty applies)', floorFound: 3, isConsumable: true, hpEffect: null, mpEffect: null, tags: 'utility,legendary,celestial,key' },
  { name: 'Broadcast Override Chip', description: 'A small device that, when activated, pushes your current feed to every viewer channel simultaneously for 60 seconds regardless of which crawler they were watching. Your viewer count will never be the same afterwards. In either direction.', tier: 'legendary', lootBoxTier: 'celestial', slot: null, effortType: null, skillBonus: 'Activate: all dungeon viewers see your feed for 60s. Viewer count x10 or /2 depending on what happens.', floorFound: 3, isConsumable: true, hpEffect: null, mpEffect: null, tags: 'utility,legendary,celestial,fame' },
  { name: 'The Last Healing Word', description: 'A spoken incantation stored in a crystalline vial. When shattered, it heals every living crawler currently in the dungeon to full HP. Every one of them. Including the ones trying to kill you.', tier: 'legendary', lootBoxTier: 'celestial', slot: null, effortType: 'magic', skillBonus: 'Full HP to ALL living crawlers in the dungeon (friend and foe)', floorFound: 3, isConsumable: true, hpEffect: 999, mpEffect: null, tags: 'consumable,magic,legendary,celestial' },
  { name: 'Exit Pass (Unverified)', description: 'A pass that claims to allow immediate safe exit from the dungeon. The fine print is extensive. The System will not confirm whether it works. Three crawlers have tried it. Their records are sealed.', tier: 'legendary', lootBoxTier: 'celestial', slot: null, effortType: null, skillBonus: 'Claim immediate dungeon exit. Outcome at GM discretion. Records sealed.', floorFound: 3, isConsumable: true, hpEffect: null, mpEffect: null, tags: 'utility,legendary,celestial,mystery' },
]

export async function seedTier2Items() {
  console.log(`[Seed] Importing ${TIER2_ITEMS.length} tier-2 items (gold/platinum/legendary/celestial)...`)
  let added = 0
  for (const item of TIER2_ITEMS) {
    try {
      await db.insert(items).values({
        name: item.name,
        description: item.description,
        tier: item.tier,
        lootBoxTier: item.lootBoxTier,
        slot: item.slot ?? null,
        effortType: item.effortType ?? null,
        skillBonus: item.skillBonus ?? null,
        floorFound: item.floorFound ?? 1,
        isConsumable: item.isConsumable ?? false,
        hpEffect: item.hpEffect ?? null,
        mpEffect: item.mpEffect ?? null,
        tags: item.tags ?? '',
      }).onConflictDoNothing()
      added++
    } catch (e: any) {
      // skip duplicates silently
    }
  }
  console.log(`[Seed] Tier-2 items imported: ${added}`)
}
