FROM node:22-slim

WORKDIR /app

COPY package*.json ./
COPY server/package*.json ./server/

RUN npm install --workspace=server

COPY server/ ./server/

RUN npm run build --workspace=server

COPY startup.sh ./startup.sh
RUN chmod +x ./startup.sh

EXPOSE 3001

CMD ["./startup.sh"]
